/-
  Engine/DichotomyEngine.lean

  Purpose:
    Formalize the central "honest engine law":

      At every legal state:
        Close ∨ strictly paid legal step.

    Therefore:
      If Close never occurs, the local dichotomy generates a
      ClosedPaidFactory, hence an impossible infinite closed paid run.

  This file is intentionally abstract. Step00 / Twin / Riemann modules should
  instantiate it by proving their own local dichotomy lemmas.

  Assumes the project module:
    EuclidsPath.Engine.ClosedUniverse

  Required names expected from ClosedUniverse:
    ClosedPaidDynamics
    no_infinite_closed_paid_run

  If your local namespace is different, adjust the import/open lines.
-/

import Mathlib
import EuclidsPath.Engine.ClosedUniverse

set_option autoImplicit false

namespace EuclidsPath.Engine.Dichotomy

open scoped BigOperators
open EuclidsPath.ClosedUniverse

/-!
# Part I. Closed paid factory

A factory is the canonical "eternal engine":

* a closed paid dynamics;
* a seed in the legal universe;
* a successor from every legal state.

The generic theorem says such a factory cannot exist.
-/

/--
A factory form of an impossible closed paid engine.

It provides:
1. a closed paid dynamics;
2. a legal seed;
3. a successor from every legal state.
-/
structure ClosedPaidFactory where

  State :
    Type

  Step :
    State → State → Prop

  dyn :
    ClosedPaidDynamics State Step

  seed :
    State

  seed_in_universe :
    dyn.Universe seed

  next :
    ∀ x,
      dyn.Universe x →
        ∃ y, Step x y

/--
Choose the next legal state.

Important:
this definition returns a `Type`, so use `Classical.choose` instead of
destructing an existential from `Prop`.
-/
noncomputable def ClosedPaidFactory.nextU
  (F : ClosedPaidFactory)
  (x : {s : F.State // F.dyn.Universe s}) :
    {y : {s : F.State // F.dyn.Universe s} //
      F.Step x.1 y.1} := by
  classical

  let y : F.State :=
    Classical.choose (F.next x.1 x.2)

  have hy :
      F.Step x.1 y :=
    Classical.choose_spec (F.next x.1 x.2)

  have hyU :
      F.dyn.Universe y :=
    F.dyn.closed x.2 hy

  exact ⟨⟨y, hyU⟩, hy⟩

/--
The infinite legal path generated by a factory.
-/
noncomputable def ClosedPaidFactory.pathU
  (F : ClosedPaidFactory) :
    ℕ → {s : F.State // F.dyn.Universe s}
| 0 =>
    ⟨F.seed, F.seed_in_universe⟩
| n + 1 =>
    (F.nextU (ClosedPaidFactory.pathU F n)).1

/--
Every adjacent pair in the generated path is connected by `Step`.
-/
theorem ClosedPaidFactory.pathU_step
  (F : ClosedPaidFactory) :
    ∀ n,
      F.Step
        (ClosedPaidFactory.pathU F n).1
        (ClosedPaidFactory.pathU F (n+1)).1 := by
  intro n
  change F.Step
    (ClosedPaidFactory.pathU F n).1
    ((F.nextU (ClosedPaidFactory.pathU F n)).1).1
  exact (F.nextU (ClosedPaidFactory.pathU F n)).2

/--
No closed paid factory exists.

A factory produces an infinite closed paid run, contradicting
`no_infinite_closed_paid_run`.
-/
theorem no_closedPaidFactory :
    ¬ Nonempty ClosedPaidFactory := by
  intro h
  rcases h with ⟨F⟩

  exact no_infinite_closed_paid_run F.dyn
    ⟨
      (fun n => (ClosedPaidFactory.pathU F n).1),
      (ClosedPaidFactory.pathU F 0).2,
      ClosedPaidFactory.pathU_step F
    ⟩

/-!
# Part II. DichotomyEngine

The engine law:

  At every legal state, either Close occurs or there is a strictly paid
  legal step.

This prevents all cheating modes at once:
* stopping without Close;
* leaving the universe;
* refuelling;
* zero-work no-op;
* unaccounted continuation.
-/

/--
A dichotomy engine.

The fields say:

* `Universe` is the legal domain.
* `Total` is a finite natural potential.
* `Work` is the cost of a step.
* `step_or_close` is the local dichotomy:
    every legal state closes or has a successor.
* `step_preserves` says the step cannot leave the universe.
* `step_paid` says the step cannot refuel.
* `work_pos` says the step is not a zero-work no-op.
-/
structure DichotomyEngine
  (State : Type)
  (Close : State → Prop)
  (Step : State → State → Prop) where

  Universe :
    State → Prop

  Total :
    State → ℕ

  Work :
    State → State → ℕ

  step_or_close :
    ∀ x,
      Universe x →
        Close x ∨ ∃ y, Step x y

  step_preserves :
    ∀ {x y},
      Universe x →
      Step x y →
        Universe y

  step_paid :
    ∀ {x y},
      Universe x →
      Step x y →
        Total y + Work x y ≤ Total x

  work_pos :
    ∀ {x y},
      Universe x →
      Step x y →
        0 < Work x y

/--
The closed paid dynamics hidden inside a `DichotomyEngine`.
-/
def DichotomyEngine.toClosedPaidDynamics
  {State : Type}
  {Close : State → Prop}
  {Step : State → State → Prop}
  (E : DichotomyEngine State Close Step) :
    ClosedPaidDynamics State Step :=
{
  Universe := E.Universe
  Total := E.Total
  Work := E.Work
  closed := E.step_preserves
  paid := E.step_paid
  work_pos := E.work_pos
}

/--
If Close is impossible everywhere in the legal universe, a dichotomy engine
becomes a closed paid factory.
-/
def factory_of_no_close
  {State : Type}
  {Close : State → Prop}
  {Step : State → State → Prop}
  (E : DichotomyEngine State Close Step)
  (seed : State)
  (hSeed : E.Universe seed)
  (hNoClose :
    ∀ x, E.Universe x → ¬ Close x) :
    ClosedPaidFactory :=
{
  State := State

  Step := Step

  dyn := E.toClosedPaidDynamics

  seed := seed

  seed_in_universe := hSeed

  next := by
    intro x hx
    rcases E.step_or_close x hx with hClose | hNext
    · exact False.elim (hNoClose x hx hClose)
    · exact hNext
}

/--
Main theorem:
in a dichotomy engine, starting from a legal seed, some legal state must close.

If not, `factory_of_no_close` produces an impossible closed paid factory.
-/
theorem close_forced
  {State : Type}
  {Close : State → Prop}
  {Step : State → State → Prop}
  (E : DichotomyEngine State Close Step)
  (seed : State)
  (hSeed : E.Universe seed) :
    ∃ x, E.Universe x ∧ Close x := by
  by_contra hNo

  have hNoClose :
      ∀ x, E.Universe x → ¬ Close x := by
    intro x hx hClose
    exact hNo ⟨x, hx, hClose⟩

  have hFactory :
      Nonempty ClosedPaidFactory :=
    ⟨factory_of_no_close E seed hSeed hNoClose⟩

  exact no_closedPaidFactory hFactory

/--
Equivalent no-close contradiction form.
-/
theorem contradiction_of_no_close
  {State : Type}
  {Close : State → Prop}
  {Step : State → State → Prop}
  (E : DichotomyEngine State Close Step)
  (seed : State)
  (hSeed : E.Universe seed)
  (hNoClose :
    ∀ x, E.Universe x → ¬ Close x) :
    False := by
  exact no_closedPaidFactory
    ⟨factory_of_no_close E seed hSeed hNoClose⟩

/-!
# Part III. Local dichotomy package

Sometimes it is more convenient to define a raw local theorem:

  Close x ∨ ∃ y,
    Universe y ∧ Step x y ∧ Paid x y ∧ WorkPositive x y

and then package it into `DichotomyEngine`.
-/

/--
One-step local result with all honest-engine conditions bundled at the
successor.
-/
def LocalPaidDichotomy
  {State : Type}
  (Universe : State → Prop)
  (Close : State → Prop)
  (Step : State → State → Prop)
  (Total : State → ℕ)
  (Work : State → State → ℕ) : Prop :=
  ∀ x,
    Universe x →
      Close x ∨
      ∃ y,
        Universe y ∧
        Step x y ∧
        Total y + Work x y ≤ Total x ∧
        0 < Work x y

/--
Build a `DichotomyEngine` from a bundled local dichotomy.

This construction uses the bundled `Universe y`, `paid`, and `work_pos`
proofs by looking back at the local dichotomy for a given step.
Because a raw `Step x y` may have many possible witnesses, this builder
requires separate global proofs of preservation/payment/positivity.

Use this when `Step` is already defined so that these properties are global.
-/
def DichotomyEngine.of_parts
  {State : Type}
  {Close : State → Prop}
  {Step : State → State → Prop}
  (Universe : State → Prop)
  (Total : State → ℕ)
  (Work : State → State → ℕ)
  (step_or_close :
    ∀ x,
      Universe x →
        Close x ∨ ∃ y, Step x y)
  (step_preserves :
    ∀ {x y},
      Universe x →
      Step x y →
        Universe y)
  (step_paid :
    ∀ {x y},
      Universe x →
      Step x y →
        Total y + Work x y ≤ Total x)
  (work_pos :
    ∀ {x y},
      Universe x →
      Step x y →
        0 < Work x y) :
    DichotomyEngine State Close Step :=
{
  Universe := Universe
  Total := Total
  Work := Work
  step_or_close := step_or_close
  step_preserves := step_preserves
  step_paid := step_paid
  work_pos := work_pos
}

/-!
# Part IV. Violation-to-close patterns

These are the local "no cheating" targets. They are not proved abstractly;
they are the exact lemmas a concrete engine must provide.

They show how all cheating modes are absorbed into the local dichotomy.
-/

/--
Universe escape event.
-/
structure UniverseEscape
  {State : Type}
  (Universe : State → Prop)
  (RawStep : State → State → Prop)
  (x y : State) : Prop where

  source_legal :
    Universe x

  raw_step :
    RawStep x y

  target_illegal :
    ¬ Universe y

/--
Refuel event: the raw transition does not satisfy the paid inequality.
-/
structure RefuelEvent
  {State : Type}
  (Universe : State → Prop)
  (RawStep : State → State → Prop)
  (Total : State → ℕ)
  (Work : State → State → ℕ)
  (x y : State) : Prop where

  source_legal :
    Universe x

  raw_step :
    RawStep x y

  refuel :
    Total x < Total y + Work x y

/--
Zero-work event: the transition makes no positive progress.
-/
structure ZeroWorkEvent
  {State : Type}
  (Universe : State → Prop)
  (RawStep : State → State → Prop)
  (Work : State → State → ℕ)
  (x y : State) : Prop where

  source_legal :
    Universe x

  raw_step :
    RawStep x y

  zero_work :
    Work x y = 0

/--
Abstract no-cheating interface for a raw transition.

A concrete Step00/Riemann/twin engine should prove these lemmas.
-/
structure NoCheatingRules
  {State : Type}
  (Universe : State → Prop)
  (Close : State → Prop)
  (RawStep : State → State → Prop)
  (Total : State → ℕ)
  (Work : State → State → ℕ) : Prop where

  universe_escape_forces_close :
    ∀ {x y},
      UniverseEscape Universe RawStep x y →
        Close x

  refuel_forces_close :
    ∀ {x y},
      RefuelEvent Universe RawStep Total Work x y →
        Close x

  zero_work_forces_close :
    ∀ {x y},
      ZeroWorkEvent Universe RawStep Work x y →
        Close x

/--
Legal paid step extracted from raw step.
-/
def LegalPaidStep
  {State : Type}
  (Universe : State → Prop)
  (RawStep : State → State → Prop)
  (Total : State → ℕ)
  (Work : State → State → ℕ)
  (x y : State) : Prop :=
  RawStep x y ∧
  Universe y ∧
  Total y + Work x y ≤ Total x ∧
  0 < Work x y

/--
If a raw transition exists and no cheating event can occur without Close,
then under `¬ Close x` it yields a legal paid step.

This is often the local proof pattern behind `step_or_close`.
-/
theorem legalPaidStep_of_rawStep_noClose
  {State : Type}
  {Universe : State → Prop}
  {Close : State → Prop}
  {RawStep : State → State → Prop}
  {Total : State → ℕ}
  {Work : State → State → ℕ}
  (Rules : NoCheatingRules Universe Close RawStep Total Work)
  {x y : State}
  (hUx : Universe x)
  (hRaw : RawStep x y)
  (hNoClose : ¬ Close x)
  (hPaidOrRefuel :
    Total y + Work x y ≤ Total x ∨
    Total x < Total y + Work x y)
  (hWorkPosOrZero :
    0 < Work x y ∨
    Work x y = 0)
  (hUniverseOrEscape :
    Universe y ∨ ¬ Universe y) :
    LegalPaidStep Universe RawStep Total Work x y := by

  rcases hUniverseOrEscape with hUy | hEsc
  · rcases hPaidOrRefuel with hPaid | hRefuel
    · rcases hWorkPosOrZero with hPos | hZero
      · exact ⟨hRaw, hUy, hPaid, hPos⟩
      · exact False.elim
          (hNoClose
            (Rules.zero_work_forces_close
              {
                source_legal := hUx
                raw_step := hRaw
                zero_work := hZero
              }))
    · exact False.elim
        (hNoClose
          (Rules.refuel_forces_close
            {
              source_legal := hUx
              raw_step := hRaw
              refuel := hRefuel
            }))
  · exact False.elim
      (hNoClose
        (Rules.universe_escape_forces_close
          {
            source_legal := hUx
            raw_step := hRaw
            target_illegal := hEsc
          }))

/-!
# Part V. Split version

For branch/cloning behavior, use a split engine:

  Close ∨ paid split.

This prevents free cloning by requiring payment of the sum of child potentials.
-/

/--
Split engine with local dichotomy:
every legal state either closes or splits into paid legal children.
-/
structure DichotomySplitEngine
  (State : Type)
  (Close : State → Prop)
  (Split : State → Finset State → Prop) where

  Universe :
    State → Prop

  Total :
    State → ℕ

  SplitWork :
    State → Finset State → ℕ

  split_or_close :
    ∀ x,
      Universe x →
        Close x ∨ ∃ kids, Split x kids

  split_preserves :
    ∀ {x kids y},
      Universe x →
      Split x kids →
      y ∈ kids →
        Universe y

  split_paid :
    ∀ {x kids},
      Universe x →
      Split x kids →
        (∑ y ∈ kids, Total y) + SplitWork x kids ≤ Total x

  split_work_pos :
    ∀ {x kids},
      Universe x →
      Split x kids →
      kids.Nonempty →
        0 < SplitWork x kids

/--
Unpaid split event.
-/
structure UnpaidSplitEvent
  {State : Type}
  (Universe : State → Prop)
  (RawSplit : State → Finset State → Prop)
  (Total : State → ℕ)
  (SplitWork : State → Finset State → ℕ)
  (x : State)
  (kids : Finset State) : Prop where

  source_legal :
    Universe x

  raw_split :
    RawSplit x kids

  unpaid :
    Total x <
      (∑ y ∈ kids, Total y) + SplitWork x kids

/--
A split engine has no free cloning if every unpaid split forces Close.
-/
structure NoFreeSplitRules
  {State : Type}
  (Universe : State → Prop)
  (Close : State → Prop)
  (RawSplit : State → Finset State → Prop)
  (Total : State → ℕ)
  (SplitWork : State → Finset State → ℕ) : Prop where

  unpaid_split_forces_close :
    ∀ {x kids},
      UnpaidSplitEvent Universe RawSplit Total SplitWork x kids →
        Close x

/-!
# Part VI. Step00 integration targets

The twin/Step00 side should instantiate this file by proving the following
kind of targets.

These are declarations as comments, not theorem assumptions.
-/

/-

def Step00Close
  (M0 N : ℕ)
  (x : Step00GlobalState) : Prop :=
  TwinAbove N ∨ Step00.EuclideanEngine x.A M0

def Step00LegalPaidStep
  (M0 N : ℕ)
  (x y : Step00GlobalState) : Prop :=
  Step00RawStep M0 N x y ∧
  Step00Universe M0 N y ∧
  Step00Total M0 N y + Step00Work M0 N x y
    ≤ Step00Total M0 N x ∧
  0 < Step00Work M0 N x y

theorem step00_local_dichotomy
  (M0 N : ℕ)
  (x : Step00GlobalState)
  (hU : Step00Universe M0 N x) :
    Step00Close M0 N x ∨
    ∃ y, Step00LegalPaidStep M0 N x y

theorem step00_dichotomyEngine
  (M0 N : ℕ) :
    DichotomyEngine
      Step00GlobalState
      (Step00Close M0 N)
      (fun x y => Step00LegalPaidStep M0 N x y)

theorem step00_close_forced
  (M0 N : ℕ)
  (seed : Step00GlobalState)
  (hSeed : Step00Universe M0 N seed) :
    ∃ x,
      Step00Universe M0 N x ∧
      Step00Close M0 N x :=
  close_forced (step00_dichotomyEngine M0 N) seed hSeed

-/

/-!
# Part VII. Riemann integration targets

The RH side should instantiate the same dichotomy with `Close := False`
or with a suitable analytic close condition.

For impossible-engine RH reduction:

  OffCriticalZero → DichotomyEngine State False Step

then `close_forced` immediately contradicts `False`.
-/

/-

def RiemannClose
  (Z : OffCriticalZero)
  (x : RiemannState Z) : Prop :=
  False

theorem riemann_local_dichotomy
  (Z : OffCriticalZero)
  (x : RiemannState Z)
  (hU : RiemannUniverse Z x) :
    RiemannClose Z x ∨
    ∃ y, RiemannLegalPaidStep Z x y

theorem riemann_dichotomyEngine
  (Z : OffCriticalZero) :
    DichotomyEngine
      (RiemannState Z)
      (RiemannClose Z)
      (fun x y => RiemannLegalPaidStep Z x y)

theorem contradiction_of_offCriticalZero_engine
  (Z : OffCriticalZero)
  (seed : RiemannState Z)
  (hSeed : RiemannUniverse Z seed) :
    False := by
  rcases close_forced (riemann_dichotomyEngine Z) seed hSeed with
    ⟨x, hxU, hxClose⟩
  exact hxClose

-/

/-!
# Part VIII. Summary

The core theorem in this file is:

```lean
close_forced :
  DichotomyEngine State Close Step →
  seed ∈ Universe →
  ∃ x, Universe x ∧ Close x
```

Interpretation:

If every legal state satisfies

```lean
Close ∨ strictly paid legal step
```

then Close is inevitable.

Therefore any attempted cheating mode must be absorbed into the local
dichotomy:

* universe escape;
* refuel;
* zero-work no-op;
* free split/cloning;
* unaccounted carrier regeneration;
* unpaid promotion.

For Step00 and Riemann, the remaining mathematical work is to prove their
local dichotomy lemmas.
-/

end EuclidsPath.Engine.Dichotomy
