import EuclidsPath.Engine.Step00PhaseCoverKernel

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Kernel gap brackets at 41 and 43 — the SAT sides

`tools/phase_cover_run1.log` (lines 106–166, run of 2026-07-10) pins the TRUE gaps at the
next two scales by the exact no-mirror solver, replica-matched by the Lean-model harness:
`G(41) = 91` (UNSAT at g = 91: 473,293 nodes, log line 117; SAT at g = 90, line 118) and
`G(43) = 103` (UNSAT at g = 103: 4,889,831 nodes, line 122; SAT at g = 102, line 123).
Those exact values are HARNESS facts.  What the kernel certifies HERE is the SAT (lower)
side of each bracket, from the solver's certificate runs re-verified by trial division
(log lines 130–131):

* `r₄₁ = 50077677123072`: all 90 centers `r+1 … r+90` are struck by a clock `≤ 41`
  (`allStruck_41`), hence `¬ CleanGapBound 41 90` — i.e. `G(41) > 90`, so `G(41) ≥ 91`.
* `r₄₃ = 233885349904190`: all 102 centers `r+1 … r+102` are struck by a clock `≤ 43`
  (`allStruck_43`), hence `¬ CleanGapBound 43 102` — i.e. `G(43) > 102`, so `G(43) ≥ 103`.

The UNSAT (upper) sides differ in cost by orders of magnitude.  At 41 the Sharp-window
tree (`g = 120 = ⌊41²/14⌋`) measures 174,254,797 cap-work (log line 138) and IS built —
the `Sharp41/PartNN` ladder assembled in `Step00Sharp41` yields `CleanGapBound 41 120`,
closing the kernel bracket `G(41) ∈ [91, 120]`.  At 43 the Sharp-window tree measures
1,665,079,448 cap-work (log line 143, ≈ 9.6× the whole 41 ladder, ≈ 24× the 37 ladder) —
pre-registered as DEFERRED, so scale 43 carries ONLY the kernel lower bracket
`G(43) ≥ 103` plus the harness-exact value `G(43) = 103`.  No kernel upper bound at 43
is claimed anywhere.

Every witness literal below was re-verified arithmetically by the generator
(`tools/gen_sharp41_lean.py`): mod check per clock per offset, plus cleanliness of the
window ends `r` and `r + G`.
-/

namespace EuclidsPath
namespace GapBracket4143

open EuclidsPath.TwinJacobsthalWall
open EuclidsPath.PhaseCoverKernel

/-- The big clocks of scale 41 (descending), `i6 = 6⁻¹ mod q` — extends the
    `bigs17 … bigs37` tables of `Step00PhaseCoverKernel` by `(41, 7)`. -/
def bigs41 : List CoverClock := [(41, 7), (37, 31), (31, 26), (29, 5), (23, 4), (19, 16), (17, 3)]

set_option maxRecDepth 100000 in
/-- SAT witness at 41 (`r = 50077677123072`, solver certificate, re-verified by trial
    division — `tools/phase_cover_run1.log` line 130): the 90 centers `r+1 … r+90` are all
    struck by a clock `≤ 41`. -/
theorem allStruck_41 : allStruckB (smallClocks ++ bigs41) 50077677123072 90 = true := by
  decide +kernel

/-- **Kernel lower bracket at 41**: `G(41) > 90` — the harness-exact `G(41) = 91`
    (log line 117) is kernel-certified from below.  The upper side `CleanGapBound 41 120`
    lands in `Step00Sharp41`, closing `G(41) ∈ [91, 120]`. -/
theorem not_cleanGapBound_41_90 : ¬ CleanGapBound 41 90 :=
  not_cleanGapBound_of_struck (by decide) allStruck_41

set_option maxRecDepth 100000 in
/-- SAT witness at 43 (`r = 233885349904190`, solver certificate, re-verified by trial
    division — `tools/phase_cover_run1.log` line 131): the 102 centers `r+1 … r+102` are
    all struck by a clock `≤ 43`. -/
theorem allStruck_43 : allStruckB (smallClocks ++ ((43, 36) :: bigs41)) 233885349904190 102 = true := by
  decide +kernel

/-- **Kernel lower bracket at 43**: `G(43) > 102` — the harness-exact `G(43) = 103`
    (log line 122) is kernel-certified from below.  HONESTY: the kernel UPPER side at 43
    is NOT built (Sharp-window tree ≈ 9.6× the whole 41 ladder — pre-registered deferral);
    scale 43 carries only this lower bracket. -/
theorem not_cleanGapBound_43_102 : ¬ CleanGapBound 43 102 :=
  not_cleanGapBound_of_struck (by decide) allStruck_43

/-! ### Margin ledger (exact integer checks): the Sharp window at the new scales -/

example : (41 : ℕ) ^ 2 / 14 = 120 := by norm_num
example : (43 : ℕ) ^ 2 / 14 = 132 := by norm_num
/-- Sharp SURVIVES at 41: `14 · 91 = 1274 ≤ 1681 = 41²` (ratio `91/120 ≈ 0.76`). -/
example : 14 * 91 ≤ 41 ^ 2 := by norm_num
/-- Sharp SURVIVES at 43: `14 · 103 = 1442 ≤ 1849 = 43²` (ratio `103/132 ≈ 0.78`). -/
example : 14 * 103 ≤ 43 ^ 2 := by norm_num

/-!
### Axiom audit (performed against the built module from a scratch file outside the repo)

    #print axioms allStruck_41             -- does not depend on any axioms
    #print axioms allStruck_43             -- does not depend on any axioms
    #print axioms not_cleanGapBound_41_90  -- [propext, Quot.sound]
    #print axioms not_cleanGapBound_43_102 -- [propext, Quot.sound]

No `sorryAx`, no `Lean.ofReduceBool`/`Lean.trustCompiler` (`native_decide` unused), no
`step00FirstCause`.
-/

end GapBracket4143
end EuclidsPath
