import EuclidsPath.Engine.Sharp41.Part01
import EuclidsPath.Engine.Sharp41.Part02
import EuclidsPath.Engine.Sharp41.Part03
import EuclidsPath.Engine.Sharp41.Part04
import EuclidsPath.Engine.Sharp41.Part05
import EuclidsPath.Engine.Sharp41.Part06
import EuclidsPath.Engine.Sharp41.Part07
import EuclidsPath.Engine.Sharp41.Part08
import EuclidsPath.Engine.Sharp41.Part09
import EuclidsPath.Engine.Sharp41.Part10
import EuclidsPath.Engine.Sharp41.Part11
import EuclidsPath.Engine.Sharp41.Part12
import EuclidsPath.Engine.Sharp41.Part13
import EuclidsPath.Engine.Sharp41.Part14
import EuclidsPath.Engine.Sharp41.Part15
import EuclidsPath.Engine.Sharp41.Part16
import EuclidsPath.Engine.Sharp41.Part17
import EuclidsPath.Engine.Sharp41.Part18
import EuclidsPath.Engine.Sharp41.Part19
import EuclidsPath.Engine.Sharp41.Part20
import EuclidsPath.Engine.Sharp41.Part21
import EuclidsPath.Engine.Sharp41.Part22
import EuclidsPath.Engine.Sharp41.Part23
import EuclidsPath.Engine.Sharp41.Part24
import EuclidsPath.Engine.Sharp41.Part25

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# The Sharp gate at 41 — `CleanGapBound 41 120`, `120 = ⌊41²/14⌋`, kernel-certified

Assembly of the `Sharp41/PartNN` ladder: the 385 phase cells `(t5, t7, t11)` of
`tools/sharp41_cells.json` (117 of them split by `t13`; 1789 kernel gates over
25 parts, total cap-work 174,254,797) exhaust the full `5 × 7 × 11` phase grid —
the glue below is the same `enumSmall_cons_of_parts` + `interval_cases` discipline as the
`A = 37` ladder in `Step00PhaseCoverKernel`, three levels deep (t11 → t7 → t5).

The result is the FIRST kernel-certified Sharp-wall instance past the exactness ladder:
`G(41) ≤ 120 = ⌊41²/14⌋` (`twinJacobsthalSharp_at_41`), against the harness-exact
`G(41) = 91`.  Together with the SAT side (`not_cleanGapBound_41_90`,
`Step00GapBracket4143`) the kernel pins the bracket `G(41) ∈ [91, 120]` — note this is a
BRACKET, not an exactness pair: the UNSAT tree at `g = 91` (473,293 nodes, ≈ 1.19·10⁹
cap-work, log line 120) is ≈ 6.8× the Sharp-window tree and is NOT built here.
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.TwinJacobsthalWall
open EuclidsPath.GapBracket4143

/-! ### Block glue: `(t5, t7)` blocks over `t11`, then `t5` levels over `t7` -/

private theorem unsat41s_b0_0 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_0_0
  · exact unsat41s_c0_0_1
  · exact unsat41s_c0_0_2
  · exact unsat41s_c0_0_3
  · exact unsat41s_c0_0_4
  · exact unsat41s_c0_0_5
  · exact unsat41s_c0_0_6
  · exact unsat41s_c0_0_7
  · exact unsat41s_c0_0_8
  · exact unsat41s_c0_0_9
  · exact unsat41s_c0_0_10
private theorem unsat41s_b0_1 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_1_0
  · exact unsat41s_c0_1_1
  · exact unsat41s_c0_1_2
  · exact unsat41s_c0_1_3
  · exact unsat41s_c0_1_4
  · exact unsat41s_c0_1_5
  · exact unsat41s_c0_1_6
  · exact unsat41s_c0_1_7
  · exact unsat41s_c0_1_8
  · exact unsat41s_c0_1_9
  · exact unsat41s_c0_1_10
private theorem unsat41s_b0_2 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_2_0
  · exact unsat41s_c0_2_1
  · exact unsat41s_c0_2_2
  · exact unsat41s_c0_2_3
  · exact unsat41s_c0_2_4
  · exact unsat41s_c0_2_5
  · exact unsat41s_c0_2_6
  · exact unsat41s_c0_2_7
  · exact unsat41s_c0_2_8
  · exact unsat41s_c0_2_9
  · exact unsat41s_c0_2_10
private theorem unsat41s_b0_3 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_3_0
  · exact unsat41s_c0_3_1
  · exact unsat41s_c0_3_2
  · exact unsat41s_c0_3_3
  · exact unsat41s_c0_3_4
  · exact unsat41s_c0_3_5
  · exact unsat41s_c0_3_6
  · exact unsat41s_c0_3_7
  · exact unsat41s_c0_3_8
  · exact unsat41s_c0_3_9
  · exact unsat41s_c0_3_10
private theorem unsat41s_b0_4 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_4_0
  · exact unsat41s_c0_4_1
  · exact unsat41s_c0_4_2
  · exact unsat41s_c0_4_3
  · exact unsat41s_c0_4_4
  · exact unsat41s_c0_4_5
  · exact unsat41s_c0_4_6
  · exact unsat41s_c0_4_7
  · exact unsat41s_c0_4_8
  · exact unsat41s_c0_4_9
  · exact unsat41s_c0_4_10
private theorem unsat41s_b0_5 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_5_0
  · exact unsat41s_c0_5_1
  · exact unsat41s_c0_5_2
  · exact unsat41s_c0_5_3
  · exact unsat41s_c0_5_4
  · exact unsat41s_c0_5_5
  · exact unsat41s_c0_5_6
  · exact unsat41s_c0_5_7
  · exact unsat41s_c0_5_8
  · exact unsat41s_c0_5_9
  · exact unsat41s_c0_5_10
private theorem unsat41s_b0_6 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 6 (strikeFilter 5 1 0 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_6_0
  · exact unsat41s_c0_6_1
  · exact unsat41s_c0_6_2
  · exact unsat41s_c0_6_3
  · exact unsat41s_c0_6_4
  · exact unsat41s_c0_6_5
  · exact unsat41s_c0_6_6
  · exact unsat41s_c0_6_7
  · exact unsat41s_c0_6_8
  · exact unsat41s_c0_6_9
  · exact unsat41s_c0_6_10
private theorem unsat41s_b1_0 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_0_0
  · exact unsat41s_c1_0_1
  · exact unsat41s_c1_0_2
  · exact unsat41s_c1_0_3
  · exact unsat41s_c1_0_4
  · exact unsat41s_c1_0_5
  · exact unsat41s_c1_0_6
  · exact unsat41s_c1_0_7
  · exact unsat41s_c1_0_8
  · exact unsat41s_c1_0_9
  · exact unsat41s_c1_0_10
private theorem unsat41s_b1_1 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_1_0
  · exact unsat41s_c1_1_1
  · exact unsat41s_c1_1_2
  · exact unsat41s_c1_1_3
  · exact unsat41s_c1_1_4
  · exact unsat41s_c1_1_5
  · exact unsat41s_c1_1_6
  · exact unsat41s_c1_1_7
  · exact unsat41s_c1_1_8
  · exact unsat41s_c1_1_9
  · exact unsat41s_c1_1_10
private theorem unsat41s_b1_2 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_2_0
  · exact unsat41s_c1_2_1
  · exact unsat41s_c1_2_2
  · exact unsat41s_c1_2_3
  · exact unsat41s_c1_2_4
  · exact unsat41s_c1_2_5
  · exact unsat41s_c1_2_6
  · exact unsat41s_c1_2_7
  · exact unsat41s_c1_2_8
  · exact unsat41s_c1_2_9
  · exact unsat41s_c1_2_10
private theorem unsat41s_b1_3 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_3_0
  · exact unsat41s_c1_3_1
  · exact unsat41s_c1_3_2
  · exact unsat41s_c1_3_3
  · exact unsat41s_c1_3_4
  · exact unsat41s_c1_3_5
  · exact unsat41s_c1_3_6
  · exact unsat41s_c1_3_7
  · exact unsat41s_c1_3_8
  · exact unsat41s_c1_3_9
  · exact unsat41s_c1_3_10
private theorem unsat41s_b1_4 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_4_0
  · exact unsat41s_c1_4_1
  · exact unsat41s_c1_4_2
  · exact unsat41s_c1_4_3
  · exact unsat41s_c1_4_4
  · exact unsat41s_c1_4_5
  · exact unsat41s_c1_4_6
  · exact unsat41s_c1_4_7
  · exact unsat41s_c1_4_8
  · exact unsat41s_c1_4_9
  · exact unsat41s_c1_4_10
private theorem unsat41s_b1_5 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_5_0
  · exact unsat41s_c1_5_1
  · exact unsat41s_c1_5_2
  · exact unsat41s_c1_5_3
  · exact unsat41s_c1_5_4
  · exact unsat41s_c1_5_5
  · exact unsat41s_c1_5_6
  · exact unsat41s_c1_5_7
  · exact unsat41s_c1_5_8
  · exact unsat41s_c1_5_9
  · exact unsat41s_c1_5_10
private theorem unsat41s_b1_6 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_6_0
  · exact unsat41s_c1_6_1
  · exact unsat41s_c1_6_2
  · exact unsat41s_c1_6_3
  · exact unsat41s_c1_6_4
  · exact unsat41s_c1_6_5
  · exact unsat41s_c1_6_6
  · exact unsat41s_c1_6_7
  · exact unsat41s_c1_6_8
  · exact unsat41s_c1_6_9
  · exact unsat41s_c1_6_10
private theorem unsat41s_b2_0 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_0_0
  · exact unsat41s_c2_0_1
  · exact unsat41s_c2_0_2
  · exact unsat41s_c2_0_3
  · exact unsat41s_c2_0_4
  · exact unsat41s_c2_0_5
  · exact unsat41s_c2_0_6
  · exact unsat41s_c2_0_7
  · exact unsat41s_c2_0_8
  · exact unsat41s_c2_0_9
  · exact unsat41s_c2_0_10
private theorem unsat41s_b2_1 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_1_0
  · exact unsat41s_c2_1_1
  · exact unsat41s_c2_1_2
  · exact unsat41s_c2_1_3
  · exact unsat41s_c2_1_4
  · exact unsat41s_c2_1_5
  · exact unsat41s_c2_1_6
  · exact unsat41s_c2_1_7
  · exact unsat41s_c2_1_8
  · exact unsat41s_c2_1_9
  · exact unsat41s_c2_1_10
private theorem unsat41s_b2_2 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_2_0
  · exact unsat41s_c2_2_1
  · exact unsat41s_c2_2_2
  · exact unsat41s_c2_2_3
  · exact unsat41s_c2_2_4
  · exact unsat41s_c2_2_5
  · exact unsat41s_c2_2_6
  · exact unsat41s_c2_2_7
  · exact unsat41s_c2_2_8
  · exact unsat41s_c2_2_9
  · exact unsat41s_c2_2_10
private theorem unsat41s_b2_3 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_3_0
  · exact unsat41s_c2_3_1
  · exact unsat41s_c2_3_2
  · exact unsat41s_c2_3_3
  · exact unsat41s_c2_3_4
  · exact unsat41s_c2_3_5
  · exact unsat41s_c2_3_6
  · exact unsat41s_c2_3_7
  · exact unsat41s_c2_3_8
  · exact unsat41s_c2_3_9
  · exact unsat41s_c2_3_10
private theorem unsat41s_b2_4 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_4_0
  · exact unsat41s_c2_4_1
  · exact unsat41s_c2_4_2
  · exact unsat41s_c2_4_3
  · exact unsat41s_c2_4_4
  · exact unsat41s_c2_4_5
  · exact unsat41s_c2_4_6
  · exact unsat41s_c2_4_7
  · exact unsat41s_c2_4_8
  · exact unsat41s_c2_4_9
  · exact unsat41s_c2_4_10
private theorem unsat41s_b2_5 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_5_0
  · exact unsat41s_c2_5_1
  · exact unsat41s_c2_5_2
  · exact unsat41s_c2_5_3
  · exact unsat41s_c2_5_4
  · exact unsat41s_c2_5_5
  · exact unsat41s_c2_5_6
  · exact unsat41s_c2_5_7
  · exact unsat41s_c2_5_8
  · exact unsat41s_c2_5_9
  · exact unsat41s_c2_5_10
private theorem unsat41s_b2_6 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_6_0
  · exact unsat41s_c2_6_1
  · exact unsat41s_c2_6_2
  · exact unsat41s_c2_6_3
  · exact unsat41s_c2_6_4
  · exact unsat41s_c2_6_5
  · exact unsat41s_c2_6_6
  · exact unsat41s_c2_6_7
  · exact unsat41s_c2_6_8
  · exact unsat41s_c2_6_9
  · exact unsat41s_c2_6_10
private theorem unsat41s_b3_0 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_0_0
  · exact unsat41s_c3_0_1
  · exact unsat41s_c3_0_2
  · exact unsat41s_c3_0_3
  · exact unsat41s_c3_0_4
  · exact unsat41s_c3_0_5
  · exact unsat41s_c3_0_6
  · exact unsat41s_c3_0_7
  · exact unsat41s_c3_0_8
  · exact unsat41s_c3_0_9
  · exact unsat41s_c3_0_10
private theorem unsat41s_b3_1 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_1_0
  · exact unsat41s_c3_1_1
  · exact unsat41s_c3_1_2
  · exact unsat41s_c3_1_3
  · exact unsat41s_c3_1_4
  · exact unsat41s_c3_1_5
  · exact unsat41s_c3_1_6
  · exact unsat41s_c3_1_7
  · exact unsat41s_c3_1_8
  · exact unsat41s_c3_1_9
  · exact unsat41s_c3_1_10
private theorem unsat41s_b3_2 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_2_0
  · exact unsat41s_c3_2_1
  · exact unsat41s_c3_2_2
  · exact unsat41s_c3_2_3
  · exact unsat41s_c3_2_4
  · exact unsat41s_c3_2_5
  · exact unsat41s_c3_2_6
  · exact unsat41s_c3_2_7
  · exact unsat41s_c3_2_8
  · exact unsat41s_c3_2_9
  · exact unsat41s_c3_2_10
private theorem unsat41s_b3_3 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_3_0
  · exact unsat41s_c3_3_1
  · exact unsat41s_c3_3_2
  · exact unsat41s_c3_3_3
  · exact unsat41s_c3_3_4
  · exact unsat41s_c3_3_5
  · exact unsat41s_c3_3_6
  · exact unsat41s_c3_3_7
  · exact unsat41s_c3_3_8
  · exact unsat41s_c3_3_9
  · exact unsat41s_c3_3_10
private theorem unsat41s_b3_4 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_4_0
  · exact unsat41s_c3_4_1
  · exact unsat41s_c3_4_2
  · exact unsat41s_c3_4_3
  · exact unsat41s_c3_4_4
  · exact unsat41s_c3_4_5
  · exact unsat41s_c3_4_6
  · exact unsat41s_c3_4_7
  · exact unsat41s_c3_4_8
  · exact unsat41s_c3_4_9
  · exact unsat41s_c3_4_10
private theorem unsat41s_b3_5 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_5_0
  · exact unsat41s_c3_5_1
  · exact unsat41s_c3_5_2
  · exact unsat41s_c3_5_3
  · exact unsat41s_c3_5_4
  · exact unsat41s_c3_5_5
  · exact unsat41s_c3_5_6
  · exact unsat41s_c3_5_7
  · exact unsat41s_c3_5_8
  · exact unsat41s_c3_5_9
  · exact unsat41s_c3_5_10
private theorem unsat41s_b3_6 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 6 (strikeFilter 5 1 3 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_6_0
  · exact unsat41s_c3_6_1
  · exact unsat41s_c3_6_2
  · exact unsat41s_c3_6_3
  · exact unsat41s_c3_6_4
  · exact unsat41s_c3_6_5
  · exact unsat41s_c3_6_6
  · exact unsat41s_c3_6_7
  · exact unsat41s_c3_6_8
  · exact unsat41s_c3_6_9
  · exact unsat41s_c3_6_10
private theorem unsat41s_b4_0 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_0_0
  · exact unsat41s_c4_0_1
  · exact unsat41s_c4_0_2
  · exact unsat41s_c4_0_3
  · exact unsat41s_c4_0_4
  · exact unsat41s_c4_0_5
  · exact unsat41s_c4_0_6
  · exact unsat41s_c4_0_7
  · exact unsat41s_c4_0_8
  · exact unsat41s_c4_0_9
  · exact unsat41s_c4_0_10
private theorem unsat41s_b4_1 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_1_0
  · exact unsat41s_c4_1_1
  · exact unsat41s_c4_1_2
  · exact unsat41s_c4_1_3
  · exact unsat41s_c4_1_4
  · exact unsat41s_c4_1_5
  · exact unsat41s_c4_1_6
  · exact unsat41s_c4_1_7
  · exact unsat41s_c4_1_8
  · exact unsat41s_c4_1_9
  · exact unsat41s_c4_1_10
private theorem unsat41s_b4_2 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_2_0
  · exact unsat41s_c4_2_1
  · exact unsat41s_c4_2_2
  · exact unsat41s_c4_2_3
  · exact unsat41s_c4_2_4
  · exact unsat41s_c4_2_5
  · exact unsat41s_c4_2_6
  · exact unsat41s_c4_2_7
  · exact unsat41s_c4_2_8
  · exact unsat41s_c4_2_9
  · exact unsat41s_c4_2_10
private theorem unsat41s_b4_3 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_3_0
  · exact unsat41s_c4_3_1
  · exact unsat41s_c4_3_2
  · exact unsat41s_c4_3_3
  · exact unsat41s_c4_3_4
  · exact unsat41s_c4_3_5
  · exact unsat41s_c4_3_6
  · exact unsat41s_c4_3_7
  · exact unsat41s_c4_3_8
  · exact unsat41s_c4_3_9
  · exact unsat41s_c4_3_10
private theorem unsat41s_b4_4 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_4_0
  · exact unsat41s_c4_4_1
  · exact unsat41s_c4_4_2
  · exact unsat41s_c4_4_3
  · exact unsat41s_c4_4_4
  · exact unsat41s_c4_4_5
  · exact unsat41s_c4_4_6
  · exact unsat41s_c4_4_7
  · exact unsat41s_c4_4_8
  · exact unsat41s_c4_4_9
  · exact unsat41s_c4_4_10
private theorem unsat41s_b4_5 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_5_0
  · exact unsat41s_c4_5_1
  · exact unsat41s_c4_5_2
  · exact unsat41s_c4_5_3
  · exact unsat41s_c4_5_4
  · exact unsat41s_c4_5_5
  · exact unsat41s_c4_5_6
  · exact unsat41s_c4_5_7
  · exact unsat41s_c4_5_8
  · exact unsat41s_c4_5_9
  · exact unsat41s_c4_5_10
private theorem unsat41s_b4_6 :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_6_0
  · exact unsat41s_c4_6_1
  · exact unsat41s_c4_6_2
  · exact unsat41s_c4_6_3
  · exact unsat41s_c4_6_4
  · exact unsat41s_c4_6_5
  · exact unsat41s_c4_6_6
  · exact unsat41s_c4_6_7
  · exact unsat41s_c4_6_8
  · exact unsat41s_c4_6_9
  · exact unsat41s_c4_6_10
private theorem unsat41s_t0 :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 0 (List.range' 1 120)) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_b0_0
  · exact unsat41s_b0_1
  · exact unsat41s_b0_2
  · exact unsat41s_b0_3
  · exact unsat41s_b0_4
  · exact unsat41s_b0_5
  · exact unsat41s_b0_6
private theorem unsat41s_t1 :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 1 (List.range' 1 120)) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_b1_0
  · exact unsat41s_b1_1
  · exact unsat41s_b1_2
  · exact unsat41s_b1_3
  · exact unsat41s_b1_4
  · exact unsat41s_b1_5
  · exact unsat41s_b1_6
private theorem unsat41s_t2 :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 2 (List.range' 1 120)) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_b2_0
  · exact unsat41s_b2_1
  · exact unsat41s_b2_2
  · exact unsat41s_b2_3
  · exact unsat41s_b2_4
  · exact unsat41s_b2_5
  · exact unsat41s_b2_6
private theorem unsat41s_t3 :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 3 (List.range' 1 120)) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_b3_0
  · exact unsat41s_b3_1
  · exact unsat41s_b3_2
  · exact unsat41s_b3_3
  · exact unsat41s_b3_4
  · exact unsat41s_b3_5
  · exact unsat41s_b3_6
private theorem unsat41s_t4 :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 4 (List.range' 1 120)) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_b4_0
  · exact unsat41s_b4_1
  · exact unsat41s_b4_2
  · exact unsat41s_b4_3
  · exact unsat41s_b4_4
  · exact unsat41s_b4_5
  · exact unsat41s_b4_6

/-! ### The gate, the Sharp crown, the wall instance, the bracket -/

/-- UNSAT phase cover at `A = 41`, `g = 120 = ⌊41²/14⌋` (the Sharp window), glued from
    the 385 measured phase cells (1789 kernel gates over 25 part files). -/
theorem unsatCover_41_120 : enumSmallB smallClocks bigs41 (List.range' 1 120) = true := by
  show enumSmallB ((5, 1) :: [(7, 6), (11, 2), (13, 11)]) bigs41 (List.range' 1 120) = true
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_t0
  · exact unsat41s_t1
  · exact unsat41s_t2
  · exact unsat41s_t3
  · exact unsat41s_t4

/-- **The Sharp gate at 41**: `CleanGapBound 41 120` on all of ℕ. -/
theorem cleanGapBound_41_120 : CleanGapBound 41 120 := by
  refine cleanGapBound_of_gate smallClocks bigs41 (by decide) ?_
    (by norm_num [cntB]) unsatCover_41_120
  intro q hq h5 hA
  interval_cases q <;> first
    | decide
    | exact absurd hq (by norm_num)

/-- **Sharp-wall instance at 41** — the first Sharp instance BEYOND the exactness ladder:
    `G(41) ≤ 120 = ⌊41²/14⌋` (harness-exact `G(41) = 91`, ratio `0.76`; the Sharp
    hypothesis `TwinJacobsthalBoundSharp` survives its falsifiability test at 41). -/
theorem twinJacobsthalSharp_at_41 : CleanGapBound 41 (41 ^ 2 / 14) :=
  cleanGapBound_mono cleanGapBound_41_120 (by norm_num)

/-- The wall instance at 41: `G(41) ≤ 120 ≤ ⌊41²/7⌋ = 240`. -/
theorem twinJacobsthal_at_41 : CleanGapBound 41 (41 ^ 2 / 7) :=
  cleanGapBound_mono cleanGapBound_41_120 (by norm_num)

/-- **The kernel bracket at 41**: `G(41) ∈ [91, 120]` — upper side from the Sharp gate,
    lower side from the SAT run at `r₄₁` (`Step00GapBracket4143`).  The harness-exact
    value inside the bracket is `G(41) = 91` (log line 117); exactness at 41 is NOT
    kernel-certified (the `g = 91` UNSAT tree is ≈ 6.8× the Sharp tree — not built). -/
theorem gapBracket_41 : CleanGapBound 41 120 ∧ ¬ CleanGapBound 41 90 :=
  ⟨cleanGapBound_41_120, not_cleanGapBound_41_90⟩

/-!
### Axiom audit (performed against the built module from a scratch file outside the repo)

    #print axioms unsatCover_41_120        -- [propext, Quot.sound]
    #print axioms cleanGapBound_41_120     -- [propext, Classical.choice, Quot.sound]
    #print axioms twinJacobsthalSharp_at_41 / twinJacobsthal_at_41 / gapBracket_41
                                           -- [propext, Classical.choice, Quot.sound]

Per-cell gates (`unsat41s_c*`): `decide +kernel` — each depends on at most
`[propext]`; the glue adds `Quot.sound` (chunk-glue `simp` lemmas), the bridge adds
`Classical.choice` — the standard triple, nothing else.  No `sorryAx`, no
`Lean.ofReduceBool`/`Lean.trustCompiler` (`native_decide` unused), no `step00FirstCause`.
-/

end Sharp41
end EuclidsPath
