#!/usr/bin/env python3
"""Emit the Sharp-41 kernel ladder + the 41/43 SAT bracket as Lean modules.

Inputs (all measured, all re-verified here before a single literal is written):
  tools/sharp41_cells.json  -- the A = 41, g = 120 (= floor(41^2/14), Sharp window)
      UNSAT tree decomposed into 385 phase cells (t5 x t7 x t11); per-cell cap-work
      and dfs nodes; cell sums assert-equal to the undecomposed run (harness --pc cells).
  tools/gap_extremal_harness.py::lean_model_decision -- the instrumented replica of the
      Lean checker (Step00PhaseCoverKernel.lean) with `fix={q: t}` phase pinning; every
      cell and every t13 sub-cell is re-solved HERE and asserted against the JSON.

Outputs:
  EuclidsPath/Engine/Step00GapBracket4143.lean   -- SAT sides at 41 and 43 (kernel lower
      brackets: not_cleanGapBound_41_90, not_cleanGapBound_43_102); every emitted witness
      literal is re-verified arithmetically (mod check per clock per offset) first.
  EuclidsPath/Engine/Sharp41/PartNN.lean         -- the per-cell UNSAT kernel theorems,
      packed so each part predicts <= ~450 s of kernel time at the pre-registered model
      (0.06 ms per cap-work unit; PART_CAP = 7.5M units).  Cells above CEIL = 600,000
      cap-work are split by the t13 phase (13 sub-cells, glued in the same part by
      enumSmall_cons_of_parts); sub-cell cap-work is asserted to sum EXACTLY to the
      parent and to land below CEIL (if one ever exceeded CEIL the script would abort:
      a further split would need t17, which is a BIG clock -- restructuring, not pinning).
  EuclidsPath/Engine/Step00Sharp41.lean          -- the assembly: (t5,t7)-block and
      t5-level glue, unsatCover_41_120, cleanGapBound_41_120, and the crowns
      twinJacobsthalSharp_at_41 / twinJacobsthal_at_41.
  tools/sharp41_build.ps1                        -- sequential, RESUMABLE per-part build
      (lake env lean -o <olean>, one part at a time, LEAN_NUM_THREADS=1, progress
      appended to tools/sharp41_build.log; already-OK parts are skipped on re-run).

Chunk-plan constants (frozen after the mandatory standalone calibration, 2026-07-10):
  CEIL     = 600,000 cap-work per theorem (pre-registered ceiling: the measured repo
             artifact unsat37_t2_1 = 613,395 cap-work cost 7.55 GB / 37 s on the
             32 GB reference machine -- the 8 GB per-theorem gate binds through memory);
  PART_CAP = 7,500,000 cap-work per part (<= ~450 s predicted at 0.06 ms/unit).
  Measured calibration on THIS machine (cell (1,6,6), 451,799 cap-work, standalone
  `lake env lean`, LEAN_NUM_THREADS=1): 15.0 s wall = 13.0 s import baseline + ~2.0 s
  kernel (~4.4 us/unit), peak lean RSS 3.54 GB.  Linearity checked at 91,014 (+0.2 s)
  and 567,357 (+2.9 s) cap-work.  The measured rate is ~14x FASTER than the model, so
  the frozen plan is conservative on both gates.

Usage: python tools/gen_sharp41_lean.py [--dry-run]
"""

import argparse
import importlib.util
import json
import os
import sys

# ------------------------------------------------------------------ constants

CEIL = 600_000        # per-theorem cap-work ceiling (pre-registered)
PART_CAP = 7_500_000  # per-part cap-work budget (<= ~450 s at the 0.06 ms/unit model)

A41, G41, GSHARP41 = 41, 91, 120
A43, G43 = 43, 103
R41 = 50077677123072   # SAT witness start at 41 (solver certificate, log line 130)
R43 = 233885349904190  # SAT witness start at 43 (solver certificate, log line 131)

# i6 = 6^{-1} mod q for every wing clock (must match the harness LEAN_I6 table).
I6 = {5: 1, 7: 6, 11: 2, 13: 11, 17: 3, 19: 16, 23: 4, 29: 5, 31: 26, 37: 31,
      41: 7, 43: 36}
SMALLS = [(5, 1), (7, 6), (11, 2), (13, 11)]
BIGS41 = [(41, 7), (37, 31), (31, 26), (29, 5), (23, 4), (19, 16), (17, 3)]

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENGINE = os.path.join(REPO, "EuclidsPath", "Engine")
PARTS_DIR = os.path.join(ENGINE, "Sharp41")

GEN_MARK = ("-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; "
            "regenerate instead.")


def load_harness():
    spec = importlib.util.spec_from_file_location(
        "geh", os.path.join(REPO, "tools", "gap_extremal_harness.py"))
    geh = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(geh)
    return geh


# ------------------------------------------------------- arithmetic re-checks

def is_prime(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


def verify_clock_tables(geh):
    assert I6 == geh.LEAN_I6, "i6 table drifted from the harness LEAN_I6"
    for q, i6 in I6.items():
        assert is_prime(q), f"clock {q} not prime"
        assert 0 < i6 < q, f"i6 out of range at {q}"
        assert (6 * i6) % q == 1, f"6*i6 != 1 mod {q}"
        assert (2 * i6) % q != 0, f"degenerate two-phase branch at {q}"
    got = [q for q, _ in BIGS41]
    assert got == sorted((q for q in I6 if 13 < q <= A41), reverse=True), \
        "BIGS41 must be the big clocks of scale 41, descending"
    for q, i6 in SMALLS + BIGS41:
        assert I6[q] == i6, f"clock pair ({q}, {i6}) contradicts the i6 table"


def verify_sat_window(r, A, G):
    """Trial-division re-verification of a SAT witness: r clean, r+G clean, and
    EVERY center r+1 .. r+G-1 struck by some clock q <= A (mod check per clock
    per offset -- the exact arithmetic content of allStruckB)."""
    clocks = [q for q in sorted(I6) if q <= A]

    def struck(m):
        return any((6 * m - 1) % q == 0 or (6 * m + 1) % q == 0 for q in clocks)

    assert not struck(r), f"A={A}: r={r} is not clean"
    assert not struck(r + G), f"A={A}: r+G={r + G} is not clean"
    for off in range(1, G):
        assert struck(r + off), f"A={A}: offset {off} of r={r} not struck"
    return clocks


# ------------------------------------------------------------- cell re-solves

def load_and_verify_cells(geh):
    with open(os.path.join(REPO, "tools", "sharp41_cells.json"), encoding="ascii") as f:
        data = json.load(f)
    assert (data["A"], data["g"], data["G"]) == (A41, GSHARP41, G41)
    cells = data["cells"]
    assert data["n_cells"] == len(cells) == 5 * 7 * 11 == 385
    assert {(c["t5"], c["t7"], c["t11"]) for c in cells} == \
        {(a, b, c) for a in range(5) for b in range(7) for c in range(11)}, \
        "cells must exhaust the full t5 x t7 x t11 grid"
    tot_cap = sum(c["cap_work"] for c in cells)
    tot_nodes = sum(c["nodes"] for c in cells)
    assert tot_cap == data["total_cap_work"]
    assert tot_nodes == data["total_nodes"]
    assert max(c["cap_work"] for c in cells) == data["max_cell_cap_work"]
    # re-solve EVERY cell against the pinned lean-model replica
    for c in cells:
        unsat, st = geh.lean_model_decision(
            GSHARP41, A41, fix={5: c["t5"], 7: c["t7"], 11: c["t11"]})
        assert unsat, f"cell {c} must be UNSAT"
        assert st["cap_work"] == c["cap_work"] and st["nodes"] == c["nodes"], \
            f"cell {c} re-solve mismatch: {st['cap_work']}, {st['nodes']}"
    # undecomposed cross-check
    unsat, st = geh.lean_model_decision(GSHARP41, A41)
    assert unsat and st["cap_work"] == tot_cap and st["nodes"] == tot_nodes, \
        "undecomposed run disagrees with the cell sums"
    return data, cells


def split_big_cells(geh, cells):
    """Cells above CEIL are split by t13; each sub-cell is re-solved, the 13
    sub-cell cap-works must sum EXACTLY to the parent and each must be < CEIL
    (a residual > CEIL would require restructuring around t17 -- abort loudly)."""
    units = []
    n_split = 0
    for c in cells:
        if c["cap_work"] <= CEIL:
            units.append(dict(c, subs=None))
            continue
        n_split += 1
        subs = []
        for t13 in range(13):
            unsat, st = geh.lean_model_decision(
                GSHARP41, A41,
                fix={5: c["t5"], 7: c["t7"], 11: c["t11"], 13: t13})
            assert unsat, f"sub-cell {c} t13={t13} must be UNSAT"
            assert st["cap_work"] < CEIL, (
                f"sub-cell {c} t13={t13} still exceeds CEIL "
                f"({st['cap_work']}) -- would need a t17 restructuring; ABORT")
            subs.append(dict(t13=t13, cap_work=st["cap_work"], nodes=st["nodes"]))
        assert sum(s["cap_work"] for s in subs) == c["cap_work"], \
            f"sub-cell cap-work does not sum to parent at {c}"
        assert sum(s["nodes"] for s in subs) == c["nodes"], \
            f"sub-cell nodes do not sum to parent at {c}"
        units.append(dict(c, subs=subs))
    return units, n_split


def pack_parts(units):
    """Greedy sequential packing (units stay in JSON order: descending cap-work,
    deterministic).  A split cell travels as ONE unit (its 13 sub-cells + glue
    stay in the same part)."""
    parts, cur, cur_w = [], [], 0
    for u in units:
        if cur and cur_w + u["cap_work"] > PART_CAP:
            parts.append(cur)
            cur, cur_w = [], 0
        cur.append(u)
        cur_w += u["cap_work"]
    if cur:
        parts.append(cur)
    for p in parts:
        assert sum(u["cap_work"] for u in p) <= PART_CAP
    assert sum(len(p) for p in parts) == len(units)
    return parts


# --------------------------------------------------------------- Lean emission

def cell_name(u):
    return f"unsat41s_c{u['t5']}_{u['t7']}_{u['t11']}"


def strike_prefix(u, with_t13=None):
    """The nested strikeFilter term for a pinned cell (innermost clock first: 5, 7, 11[, 13])."""
    s = (f"(strikeFilter 11 2 {u['t11']} (strikeFilter 7 6 {u['t7']} "
         f"(strikeFilter 5 1 {u['t5']} (List.range' 1 {GSHARP41}))))")
    if with_t13 is not None:
        s = f"(strikeFilter 13 11 {with_t13} {s})"
    return s


def emit_whole_cell(u):
    return f"""set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = ({u['t5']}, {u['t7']}, {u['t11']})` — cap-work {u['cap_work']:,}, nodes {u['nodes']:,} (measured, re-verified). -/
theorem {cell_name(u)} :
    enumSmallB [(13, 11)] bigs41
      {strike_prefix(u)} = true := by
  decide +kernel
"""


def emit_split_cell(u):
    out = []
    for s in u["subs"]:
        out.append(f"""set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = {s['t13']}: cap-work {s['cap_work']:,}, nodes {s['nodes']:,}
theorem {cell_name(u)}_s{s['t13']} :
    enumSmallB [] bigs41
      {strike_prefix(u, with_t13=s['t13'])} = true := by
  decide +kernel
""")
    bullets = "\n".join(f"  · exact {cell_name(u)}_s{s['t13']}" for s in u["subs"])
    out.append(f"""/-- Cell `(t5, t7, t11) = ({u['t5']}, {u['t7']}, {u['t11']})` — cap-work {u['cap_work']:,} > {CEIL:,}:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem {cell_name(u)} :
    enumSmallB ((13, 11) :: []) bigs41
      {strike_prefix(u)} = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
{bullets}
""")
    return "\n".join(out)


def part_header(idx, n_parts, part, total_cap):
    w = sum(u["cap_work"] for u in part)
    n_thm = sum(1 if u["subs"] is None else len(u["subs"]) + 1 for u in part)
    cells_list = ", ".join(f"({u['t5']},{u['t7']},{u['t11']})" for u in part)
    return f"""import EuclidsPath.Engine.Step00GapBracket4143

{GEN_MARK}

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part {idx:02d}/{n_parts:02d} (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
{CEIL:,} cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: {len(part)} cells ({cells_list}), {n_thm} kernel gates,
cap-work {w:,} ({100.0 * w / total_cap:.1f}% of the ladder's {total_cap:,}).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

"""


def emit_part(idx, n_parts, part, total_cap):
    body = []
    for u in part:
        body.append(emit_whole_cell(u) if u["subs"] is None else emit_split_cell(u))
    return part_header(idx, n_parts, part, total_cap) + "\n".join(body) + """
end Sharp41
end EuclidsPath
"""


def emit_bracket():
    """The SAT sides at 41 and 43 (verified arithmetically in verify_sat_window
    before this function is allowed to run)."""
    clocks43 = "(43, 36) :: bigs41"
    return f"""import EuclidsPath.Engine.Step00PhaseCoverKernel

{GEN_MARK}

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Kernel gap brackets at 41 and 43 — the SAT sides

`tools/phase_cover_run1.log` (lines 106–166, run of 2026-07-10) pins the TRUE gaps at the
next two scales by the exact no-mirror solver, replica-matched by the Lean-model harness:
`G(41) = 91` (UNSAT at g = 91: 473,293 nodes, log line 117; SAT at g = 90, line 118) and
`G(43) = 103` (UNSAT at g = 103: 4,889,831 nodes, line 122; SAT at g = 102, line 123).
Those exact values are HARNESS facts.  What the kernel certifies HERE is the SAT (lower)
side of each bracket, from the solver's certificate runs re-verified by trial division
(log lines 130–131):

* `r₄₁ = {R41}`: all 90 centers `r+1 … r+90` are struck by a clock `≤ 41`
  (`allStruck_41`), hence `¬ CleanGapBound 41 90` — i.e. `G(41) > 90`, so `G(41) ≥ 91`.
* `r₄₃ = {R43}`: all 102 centers `r+1 … r+102` are struck by a clock `≤ 43`
  (`allStruck_43`), hence `¬ CleanGapBound 43 102` — i.e. `G(43) > 102`, so `G(43) ≥ 103`.

The UNSAT (upper) sides differ in cost by orders of magnitude.  At 41 the Sharp-window
tree (`g = 120 = ⌊41²/14⌋`) measures 174,254,797 cap-work (log line 138) and IS built —
the `Sharp41/PartNN` ladder assembled in `Step00Sharp41` yields `CleanGapBound 41 120`,
closing the kernel bracket `G(41) ∈ [91, 120]`.  At 43 the Sharp-window tree measures
1,665,079,448 cap-work (log line 143, ≈ 9.6× the whole 41 ladder, ≈ 24× the 37 ladder) —
pre-registered as DEFERRED, so scale 43 carries ONLY the kernel lower bracket
`G(43) ≥ 103` plus the harness-exact value `G(43) = 103`.  No kernel upper bound at 43
is claimed anywhere.

Every witness literal below was re-verified arithmetically by the generator
(`tools/gen_sharp41_lean.py`): mod check per clock per offset, plus cleanliness of the
window ends `r` and `r + G`.
-/

namespace EuclidsPath
namespace GapBracket4143

open EuclidsPath.TwinJacobsthalWall
open EuclidsPath.PhaseCoverKernel

/-- The big clocks of scale 41 (descending), `i6 = 6⁻¹ mod q` — extends the
    `bigs17 … bigs37` tables of `Step00PhaseCoverKernel` by `(41, 7)`. -/
def bigs41 : List CoverClock := [(41, 7), (37, 31), (31, 26), (29, 5), (23, 4), (19, 16), (17, 3)]

set_option maxRecDepth 100000 in
/-- SAT witness at 41 (`r = {R41}`, solver certificate, re-verified by trial
    division — `tools/phase_cover_run1.log` line 130): the 90 centers `r+1 … r+90` are all
    struck by a clock `≤ 41`. -/
theorem allStruck_41 : allStruckB (smallClocks ++ bigs41) {R41} 90 = true := by
  decide +kernel

/-- **Kernel lower bracket at 41**: `G(41) > 90` — the harness-exact `G(41) = 91`
    (log line 117) is kernel-certified from below.  The upper side `CleanGapBound 41 120`
    lands in `Step00Sharp41`, closing `G(41) ∈ [91, 120]`. -/
theorem not_cleanGapBound_41_90 : ¬ CleanGapBound 41 90 :=
  not_cleanGapBound_of_struck (by decide) allStruck_41

set_option maxRecDepth 100000 in
/-- SAT witness at 43 (`r = {R43}`, solver certificate, re-verified by trial
    division — `tools/phase_cover_run1.log` line 131): the 102 centers `r+1 … r+102` are
    all struck by a clock `≤ 43`. -/
theorem allStruck_43 : allStruckB (smallClocks ++ ({clocks43})) {R43} 102 = true := by
  decide +kernel

/-- **Kernel lower bracket at 43**: `G(43) > 102` — the harness-exact `G(43) = 103`
    (log line 122) is kernel-certified from below.  HONESTY: the kernel UPPER side at 43
    is NOT built (Sharp-window tree ≈ 9.6× the whole 41 ladder — pre-registered deferral);
    scale 43 carries only this lower bracket. -/
theorem not_cleanGapBound_43_102 : ¬ CleanGapBound 43 102 :=
  not_cleanGapBound_of_struck (by decide) allStruck_43

/-! ### Margin ledger (exact integer checks): the Sharp window at the new scales -/

example : (41 : ℕ) ^ 2 / 14 = 120 := by norm_num
example : (43 : ℕ) ^ 2 / 14 = 132 := by norm_num
/-- Sharp SURVIVES at 41: `14 · 91 = 1274 ≤ 1681 = 41²` (ratio `91/120 ≈ 0.76`). -/
example : 14 * 91 ≤ 41 ^ 2 := by norm_num
/-- Sharp SURVIVES at 43: `14 · 103 = 1442 ≤ 1849 = 43²` (ratio `103/132 ≈ 0.78`). -/
example : 14 * 103 ≤ 43 ^ 2 := by norm_num

/-!
### Axiom audit (performed against the built module from a scratch file outside the repo)

    #print axioms allStruck_41             -- does not depend on any axioms
    #print axioms allStruck_43             -- does not depend on any axioms
    #print axioms not_cleanGapBound_41_90  -- [propext, Quot.sound]
    #print axioms not_cleanGapBound_43_102 -- [propext, Quot.sound]

No `sorryAx`, no `Lean.ofReduceBool`/`Lean.trustCompiler` (`native_decide` unused), no
`step00FirstCause`.
-/

end GapBracket4143
end EuclidsPath
"""


def emit_assembly(units, parts):
    n_parts = len(parts)
    total_cap = sum(u["cap_work"] for u in units)
    n_split = sum(1 for u in units if u["subs"] is not None)
    n_gates = sum(1 if u["subs"] is None else len(u["subs"]) for u in units)
    imports = "\n".join(
        f"import EuclidsPath.Engine.Sharp41.Part{i + 1:02d}" for i in range(n_parts))
    blocks = []
    for t5 in range(5):
        for t7 in range(7):
            bullets = "\n".join(f"  · exact unsat41s_c{t5}_{t7}_{t11}"
                                for t11 in range(11))
            blocks.append(f"""private theorem unsat41s_b{t5}_{t7} :
    enumSmallB ((11, 2) :: [(13, 11)]) bigs41
      (strikeFilter 7 6 {t7} (strikeFilter 5 1 {t5} (List.range' 1 {GSHARP41}))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
{bullets}
""")
    for t5 in range(5):
        bullets = "\n".join(f"  · exact unsat41s_b{t5}_{t7}" for t7 in range(7))
        blocks.append(f"""private theorem unsat41s_t{t5} :
    enumSmallB ((7, 6) :: [(11, 2), (13, 11)]) bigs41
      (strikeFilter 5 1 {t5} (List.range' 1 {GSHARP41})) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
{bullets}
""")
    top_bullets = "\n".join(f"  · exact unsat41s_t{t5}" for t5 in range(5))
    return f"""{imports}

{GEN_MARK}

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# The Sharp gate at 41 — `CleanGapBound 41 120`, `120 = ⌊41²/14⌋`, kernel-certified

Assembly of the `Sharp41/PartNN` ladder: the 385 phase cells `(t5, t7, t11)` of
`tools/sharp41_cells.json` ({n_split} of them split by `t13`; {n_gates} kernel gates over
{n_parts} parts, total cap-work {total_cap:,}) exhaust the full `5 × 7 × 11` phase grid —
the glue below is the same `enumSmall_cons_of_parts` + `interval_cases` discipline as the
`A = 37` ladder in `Step00PhaseCoverKernel`, three levels deep (t11 → t7 → t5).

The result is the FIRST kernel-certified Sharp-wall instance past the exactness ladder:
`G(41) ≤ 120 = ⌊41²/14⌋` (`twinJacobsthalSharp_at_41`), against the harness-exact
`G(41) = 91`.  Together with the SAT side (`not_cleanGapBound_41_90`,
`Step00GapBracket4143`) the kernel pins the bracket `G(41) ∈ [91, 120]` — note this is a
BRACKET, not an exactness pair: the UNSAT tree at `g = 91` (473,293 nodes, ≈ 1.19·10⁹
cap-work, log line 120) is ≈ 6.8× the Sharp-window tree and is NOT built here.
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.TwinJacobsthalWall
open EuclidsPath.GapBracket4143

/-! ### Block glue: `(t5, t7)` blocks over `t11`, then `t5` levels over `t7` -/

{"".join(blocks)}
/-! ### The gate, the Sharp crown, the wall instance, the bracket -/

/-- UNSAT phase cover at `A = 41`, `g = 120 = ⌊41²/14⌋` (the Sharp window), glued from
    the 385 measured phase cells ({n_gates} kernel gates over {n_parts} part files). -/
theorem unsatCover_41_120 : enumSmallB smallClocks bigs41 (List.range' 1 {GSHARP41}) = true := by
  show enumSmallB ((5, 1) :: [(7, 6), (11, 2), (13, 11)]) bigs41 (List.range' 1 {GSHARP41}) = true
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
{top_bullets}

/-- **The Sharp gate at 41**: `CleanGapBound 41 120` on all of ℕ. -/
theorem cleanGapBound_41_120 : CleanGapBound 41 120 := by
  refine cleanGapBound_of_gate smallClocks bigs41 (by decide) ?_
    (by norm_num [cntB]) unsatCover_41_120
  intro q hq h5 hA
  interval_cases q <;> first
    | decide
    | exact absurd hq (by norm_num)

/-- **Sharp-wall instance at 41** — the first Sharp instance BEYOND the exactness ladder:
    `G(41) ≤ 120 = ⌊41²/14⌋` (harness-exact `G(41) = 91`, ratio `0.76`; the Sharp
    hypothesis `TwinJacobsthalBoundSharp` survives its falsifiability test at 41). -/
theorem twinJacobsthalSharp_at_41 : CleanGapBound 41 (41 ^ 2 / 14) :=
  cleanGapBound_mono cleanGapBound_41_120 (by norm_num)

/-- The wall instance at 41: `G(41) ≤ 120 ≤ ⌊41²/7⌋ = 240`. -/
theorem twinJacobsthal_at_41 : CleanGapBound 41 (41 ^ 2 / 7) :=
  cleanGapBound_mono cleanGapBound_41_120 (by norm_num)

/-- **The kernel bracket at 41**: `G(41) ∈ [91, 120]` — upper side from the Sharp gate,
    lower side from the SAT run at `r₄₁` (`Step00GapBracket4143`).  The harness-exact
    value inside the bracket is `G(41) = 91` (log line 117); exactness at 41 is NOT
    kernel-certified (the `g = 91` UNSAT tree is ≈ 6.8× the Sharp tree — not built). -/
theorem gapBracket_41 : CleanGapBound 41 120 ∧ ¬ CleanGapBound 41 90 :=
  ⟨cleanGapBound_41_120, not_cleanGapBound_41_90⟩

/-!
### Axiom audit (performed against the built module from a scratch file outside the repo)

    #print axioms unsatCover_41_120        -- [propext, Quot.sound]
    #print axioms cleanGapBound_41_120     -- [propext, Classical.choice, Quot.sound]
    #print axioms twinJacobsthalSharp_at_41 / twinJacobsthal_at_41 / gapBracket_41
                                           -- [propext, Classical.choice, Quot.sound]

Per-cell gates (`unsat41s_c*`): `decide +kernel` — each depends on at most
`[propext]`; the glue adds `Quot.sound` (chunk-glue `simp` lemmas), the bridge adds
`Classical.choice` — the standard triple, nothing else.  No `sorryAx`, no
`Lean.ofReduceBool`/`Lean.trustCompiler` (`native_decide` unused), no `step00FirstCause`.
-/

end Sharp41
end EuclidsPath
"""


def emit_build_script(n_parts):
    steps = ["Step00GapBracket4143"] + [f"Part{i + 1:02d}" for i in range(n_parts)] \
        + ["Step00Sharp41"]
    lines = []
    for s in steps:
        if s.startswith("Part"):
            src = f"EuclidsPath\\Engine\\Sharp41\\{s}.lean"
            olean = f".lake\\build\\lib\\lean\\EuclidsPath\\Engine\\Sharp41\\{s}.olean"
        else:
            src = f"EuclidsPath\\Engine\\{s}.lean"
            olean = f".lake\\build\\lib\\lean\\EuclidsPath\\Engine\\{s}.olean"
        lines.append(f"@{{ Name = '{s}'; Src = '{src}'; Olean = '{olean}' }}")
    steps_ps = ",\n  ".join(lines)
    return f"""# GENERATED by tools/gen_sharp41_lean.py -- sequential, RESUMABLE kernel build of the
# Sharp-41 ladder: bracket module, {n_parts} part files, assembly.  One part at a time
# (LEAN_NUM_THREADS = 1), each `lake env lean -o <olean> <src>`; progress appended to
# tools/sharp41_build.log -- re-running the script skips parts already marked OK.
param([switch]$Force)

$repo = Split-Path $PSScriptRoot -Parent
Set-Location $repo
$env:LEAN_NUM_THREADS = '1'
$log = Join-Path $repo 'tools\\sharp41_build.log'

$steps = @(
  {steps_ps}
)

foreach ($s in $steps) {{
  $name = $s.Name
  if (-not $Force -and (Test-Path $log) -and
      (Select-String -Path $log -Pattern ('^OK ' + $name + ' ') -Quiet)) {{
    Write-Output ('skip ' + $name + ' (already OK in log)')
    continue
  }}
  $dir = Split-Path $s.Olean
  if (-not (Test-Path $dir)) {{ New-Item -ItemType Directory -Force $dir | Out-Null }}
  $sw = [Diagnostics.Stopwatch]::StartNew()
  lake env lean -o $s.Olean $s.Src
  $code = $LASTEXITCODE
  $sw.Stop()
  $secs = [math]::Round($sw.Elapsed.TotalSeconds, 1)
  $tag = if ($code -eq 0) {{ 'OK' }} else {{ 'FAIL' }}
  $line = ('{{0}} {{1}} exit={{2}} wall={{3}}s at {{4}}' -f $tag, $name, $code, $secs,
           (Get-Date -Format s))
  Add-Content -Path $log -Value $line
  Write-Output $line
  if ($code -ne 0) {{ exit 1 }}
}}
Add-Content -Path $log -Value ('DONE ladder at ' + (Get-Date -Format s))
Write-Output 'DONE ladder'
"""


# ----------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="verify + print the plan, write nothing")
    args = ap.parse_args()

    geh = load_harness()
    verify_clock_tables(geh)

    print("re-verifying SAT witnesses arithmetically (mod check per clock per offset) ...")
    c41 = verify_sat_window(R41, A41, G41)
    print(f"  A=41: r={R41}: r clean, r+{G41} clean, centers r+1..r+{G41 - 1} all struck "
          f"(clocks {c41})")
    c43 = verify_sat_window(R43, A43, G43)
    print(f"  A=43: r={R43}: r clean, r+{G43} clean, centers r+1..r+{G43 - 1} all struck "
          f"(clocks {c43})")
    assert R41 == geh.SAT_WITNESS_R[41] and R43 == geh.SAT_WITNESS_R[43]
    assert G41 == geh.EXPECTED_G[41] and G43 == geh.EXPECTED_G[43]

    print("re-solving all 385 cells against tools/sharp41_cells.json ...")
    data, cells = load_and_verify_cells(geh)
    print(f"  all 385 cells match (total cap-work {data['total_cap_work']:,}, "
          f"nodes {data['total_nodes']:,})")

    print(f"splitting cells above CEIL = {CEIL:,} by t13 ...")
    units, n_split = split_big_cells(geh, cells)
    n_gates = sum(1 if u["subs"] is None else len(u["subs"]) for u in units)
    max_gate = max(u["cap_work"] if u["subs"] is None else
                   max(s["cap_work"] for s in u["subs"]) for u in units)
    print(f"  {n_split} cells split into 13 t13-sub-cells each (sums exact); "
          f"{len(units) - n_split} whole cells; {n_gates} kernel gates; "
          f"max gate cap-work {max_gate:,} < {CEIL:,}")

    parts = pack_parts(units)
    total_cap = sum(u["cap_work"] for u in units)
    print(f"packing: {len(parts)} parts, PART_CAP = {PART_CAP:,} cap-work "
          f"(<= ~450 s at the 0.06 ms/unit model; measured ~4.4 us/unit => ~33 s kernel/part)")
    for i, p in enumerate(parts):
        w = sum(u["cap_work"] for u in p)
        print(f"  Part{i + 1:02d}: {len(p):3d} cells, cap-work {w:>9,}, "
              f"predicted kernel {w * 0.06e-3:6.1f} s (model) / {w * 4.4e-6:5.1f} s (measured)")

    if args.dry_run:
        print("dry run: nothing written")
        return

    os.makedirs(PARTS_DIR, exist_ok=True)
    wrote = []

    def write(path, text):
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        wrote.append(os.path.relpath(path, REPO))

    write(os.path.join(ENGINE, "Step00GapBracket4143.lean"), emit_bracket())
    for i, p in enumerate(parts):
        write(os.path.join(PARTS_DIR, f"Part{i + 1:02d}.lean"),
              emit_part(i + 1, len(parts), p, total_cap))
    write(os.path.join(ENGINE, "Step00Sharp41.lean"), emit_assembly(units, parts))
    write(os.path.join(REPO, "tools", "sharp41_build.ps1"),
          emit_build_script(len(parts)))

    # post-write audit: re-read the emitted parts and re-extract the cell grid
    import re
    seen = set()
    for i in range(len(parts)):
        with open(os.path.join(PARTS_DIR, f"Part{i + 1:02d}.lean"), encoding="utf-8") as f:
            text = f.read()
        for m in re.finditer(r"theorem unsat41s_c(\d+)_(\d+)_(\d+) :", text):
            seen.add((int(m.group(1)), int(m.group(2)), int(m.group(3))))
    assert seen == {(a, b, c) for a in range(5) for b in range(7) for c in range(11)}, \
        "post-write audit: emitted cell theorems do not exhaust the phase grid"
    print("post-write audit: the emitted cell theorems exhaust the full 5 x 7 x 11 grid")
    print("wrote:")
    for w in wrote:
        print("  " + w)


if __name__ == "__main__":
    main()
