# GENERATED by tools/gen_sharp41_lean.py -- sequential, RESUMABLE kernel build of the
# Sharp-41 ladder: bracket module, 25 part files, assembly.  One part at a time
# (LEAN_NUM_THREADS = 1), each `lake env lean -o <olean> <src>`; progress appended to
# tools/sharp41_build.log -- re-running the script skips parts already marked OK.
param([switch]$Force)

$repo = Split-Path $PSScriptRoot -Parent
Set-Location $repo
$env:LEAN_NUM_THREADS = '1'
$log = Join-Path $repo 'tools\sharp41_build.log'

$steps = @(
  @{ Name = 'Step00GapBracket4143'; Src = 'EuclidsPath\Engine\Step00GapBracket4143.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Step00GapBracket4143.olean' },
  @{ Name = 'Part01'; Src = 'EuclidsPath\Engine\Sharp41\Part01.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part01.olean' },
  @{ Name = 'Part02'; Src = 'EuclidsPath\Engine\Sharp41\Part02.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part02.olean' },
  @{ Name = 'Part03'; Src = 'EuclidsPath\Engine\Sharp41\Part03.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part03.olean' },
  @{ Name = 'Part04'; Src = 'EuclidsPath\Engine\Sharp41\Part04.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part04.olean' },
  @{ Name = 'Part05'; Src = 'EuclidsPath\Engine\Sharp41\Part05.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part05.olean' },
  @{ Name = 'Part06'; Src = 'EuclidsPath\Engine\Sharp41\Part06.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part06.olean' },
  @{ Name = 'Part07'; Src = 'EuclidsPath\Engine\Sharp41\Part07.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part07.olean' },
  @{ Name = 'Part08'; Src = 'EuclidsPath\Engine\Sharp41\Part08.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part08.olean' },
  @{ Name = 'Part09'; Src = 'EuclidsPath\Engine\Sharp41\Part09.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part09.olean' },
  @{ Name = 'Part10'; Src = 'EuclidsPath\Engine\Sharp41\Part10.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part10.olean' },
  @{ Name = 'Part11'; Src = 'EuclidsPath\Engine\Sharp41\Part11.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part11.olean' },
  @{ Name = 'Part12'; Src = 'EuclidsPath\Engine\Sharp41\Part12.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part12.olean' },
  @{ Name = 'Part13'; Src = 'EuclidsPath\Engine\Sharp41\Part13.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part13.olean' },
  @{ Name = 'Part14'; Src = 'EuclidsPath\Engine\Sharp41\Part14.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part14.olean' },
  @{ Name = 'Part15'; Src = 'EuclidsPath\Engine\Sharp41\Part15.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part15.olean' },
  @{ Name = 'Part16'; Src = 'EuclidsPath\Engine\Sharp41\Part16.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part16.olean' },
  @{ Name = 'Part17'; Src = 'EuclidsPath\Engine\Sharp41\Part17.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part17.olean' },
  @{ Name = 'Part18'; Src = 'EuclidsPath\Engine\Sharp41\Part18.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part18.olean' },
  @{ Name = 'Part19'; Src = 'EuclidsPath\Engine\Sharp41\Part19.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part19.olean' },
  @{ Name = 'Part20'; Src = 'EuclidsPath\Engine\Sharp41\Part20.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part20.olean' },
  @{ Name = 'Part21'; Src = 'EuclidsPath\Engine\Sharp41\Part21.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part21.olean' },
  @{ Name = 'Part22'; Src = 'EuclidsPath\Engine\Sharp41\Part22.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part22.olean' },
  @{ Name = 'Part23'; Src = 'EuclidsPath\Engine\Sharp41\Part23.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part23.olean' },
  @{ Name = 'Part24'; Src = 'EuclidsPath\Engine\Sharp41\Part24.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part24.olean' },
  @{ Name = 'Part25'; Src = 'EuclidsPath\Engine\Sharp41\Part25.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Sharp41\Part25.olean' },
  @{ Name = 'Step00Sharp41'; Src = 'EuclidsPath\Engine\Step00Sharp41.lean'; Olean = '.lake\build\lib\lean\EuclidsPath\Engine\Step00Sharp41.olean' }
)

foreach ($s in $steps) {
  $name = $s.Name
  if (-not $Force -and (Test-Path $log) -and
      (Select-String -Path $log -Pattern ('^OK ' + $name + ' ') -Quiet)) {
    Write-Output ('skip ' + $name + ' (already OK in log)')
    continue
  }
  $dir = Split-Path $s.Olean
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
  $sw = [Diagnostics.Stopwatch]::StartNew()
  lake env lean -o $s.Olean $s.Src
  $code = $LASTEXITCODE
  $sw.Stop()
  $secs = [math]::Round($sw.Elapsed.TotalSeconds, 1)
  $tag = if ($code -eq 0) { 'OK' } else { 'FAIL' }
  $line = ('{0} {1} exit={2} wall={3}s at {4}' -f $tag, $name, $code, $secs,
           (Get-Date -Format s))
  Add-Content -Path $log -Value $line
  Write-Output $line
  if ($code -ne 0) { exit 1 }
}
Add-Content -Path $log -Value ('DONE ladder at ' + (Get-Date -Format s))
Write-Output 'DONE ladder'
