import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 02/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 6 cells ((1,2,8), (2,3,9), (1,0,8), (2,1,9), (3,0,7), (3,2,4)), 84 kernel gates,
cap-work 7,296,838 (4.2% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_8_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c1_2_8_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 120,724, nodes 27
theorem unsat41s_c1_2_8_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 207,855, nodes 51
theorem unsat41s_c1_2_8_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 123,657, nodes 27
theorem unsat41s_c1_2_8_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_8_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c1_2_8_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 121,634, nodes 27
theorem unsat41s_c1_2_8_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 119,145, nodes 27
theorem unsat41s_c1_2_8_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 195,326, nodes 49
theorem unsat41s_c1_2_8_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,092, nodes 1
theorem unsat41s_c1_2_8_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 248,979, nodes 63
theorem unsat41s_c1_2_8_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 115,595, nodes 27
theorem unsat41s_c1_2_8_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 2, 8)` — cap-work 1,287,193 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_2_8 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_2_8_s0
  · exact unsat41s_c1_2_8_s1
  · exact unsat41s_c1_2_8_s2
  · exact unsat41s_c1_2_8_s3
  · exact unsat41s_c1_2_8_s4
  · exact unsat41s_c1_2_8_s5
  · exact unsat41s_c1_2_8_s6
  · exact unsat41s_c1_2_8_s7
  · exact unsat41s_c1_2_8_s8
  · exact unsat41s_c1_2_8_s9
  · exact unsat41s_c1_2_8_s10
  · exact unsat41s_c1_2_8_s11
  · exact unsat41s_c1_2_8_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 115,595, nodes 27
theorem unsat41s_c2_3_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c2_3_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 120,724, nodes 27
theorem unsat41s_c2_3_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 207,855, nodes 51
theorem unsat41s_c2_3_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 123,657, nodes 27
theorem unsat41s_c2_3_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,895, nodes 1
theorem unsat41s_c2_3_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 121,634, nodes 27
theorem unsat41s_c2_3_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 119,145, nodes 27
theorem unsat41s_c2_3_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 195,326, nodes 49
theorem unsat41s_c2_3_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c2_3_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 248,979, nodes 63
theorem unsat41s_c2_3_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 3, 9)` — cap-work 1,287,193 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_3_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_3_9_s0
  · exact unsat41s_c2_3_9_s1
  · exact unsat41s_c2_3_9_s2
  · exact unsat41s_c2_3_9_s3
  · exact unsat41s_c2_3_9_s4
  · exact unsat41s_c2_3_9_s5
  · exact unsat41s_c2_3_9_s6
  · exact unsat41s_c2_3_9_s7
  · exact unsat41s_c2_3_9_s8
  · exact unsat41s_c2_3_9_s9
  · exact unsat41s_c2_3_9_s10
  · exact unsat41s_c2_3_9_s11
  · exact unsat41s_c2_3_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,895, nodes 1
theorem unsat41s_c1_0_8_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 78,414, nodes 15
theorem unsat41s_c1_0_8_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_8_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 322,530, nodes 85
theorem unsat41s_c1_0_8_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_8_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 78,386, nodes 15
theorem unsat41s_c1_0_8_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_8_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,145, nodes 15
theorem unsat41s_c1_0_8_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_8_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 213,504, nodes 51
theorem unsat41s_c1_0_8_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,870, nodes 15
theorem unsat41s_c1_0_8_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,289, nodes 1
theorem unsat41s_c1_0_8_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 312,241, nodes 93
theorem unsat41s_c1_0_8_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 0, 8)` — cap-work 1,215,051 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_0_8 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_0_8_s0
  · exact unsat41s_c1_0_8_s1
  · exact unsat41s_c1_0_8_s2
  · exact unsat41s_c1_0_8_s3
  · exact unsat41s_c1_0_8_s4
  · exact unsat41s_c1_0_8_s5
  · exact unsat41s_c1_0_8_s6
  · exact unsat41s_c1_0_8_s7
  · exact unsat41s_c1_0_8_s8
  · exact unsat41s_c1_0_8_s9
  · exact unsat41s_c1_0_8_s10
  · exact unsat41s_c1_0_8_s11
  · exact unsat41s_c1_0_8_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 312,241, nodes 93
theorem unsat41s_c2_1_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c2_1_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 78,414, nodes 15
theorem unsat41s_c2_1_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 322,530, nodes 85
theorem unsat41s_c2_1_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 78,386, nodes 15
theorem unsat41s_c2_1_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 83,145, nodes 15
theorem unsat41s_c2_1_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 213,504, nodes 51
theorem unsat41s_c2_1_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 84,870, nodes 15
theorem unsat41s_c2_1_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,289, nodes 1
theorem unsat41s_c2_1_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 1, 9)` — cap-work 1,215,051 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_1_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_1_9_s0
  · exact unsat41s_c2_1_9_s1
  · exact unsat41s_c2_1_9_s2
  · exact unsat41s_c2_1_9_s3
  · exact unsat41s_c2_1_9_s4
  · exact unsat41s_c2_1_9_s5
  · exact unsat41s_c2_1_9_s6
  · exact unsat41s_c2_1_9_s7
  · exact unsat41s_c2_1_9_s8
  · exact unsat41s_c2_1_9_s9
  · exact unsat41s_c2_1_9_s10
  · exact unsat41s_c2_1_9_s11
  · exact unsat41s_c2_1_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,698, nodes 1
theorem unsat41s_c3_0_7_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 155,842, nodes 39
theorem unsat41s_c3_0_7_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,304, nodes 1
theorem unsat41s_c3_0_7_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 74,602, nodes 15
theorem unsat41s_c3_0_7_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 76,809, nodes 15
theorem unsat41s_c3_0_7_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 74,770, nodes 15
theorem unsat41s_c3_0_7_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 76,481, nodes 15
theorem unsat41s_c3_0_7_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 158,911, nodes 39
theorem unsat41s_c3_0_7_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 190,457, nodes 51
theorem unsat41s_c3_0_7_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c3_0_7_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 73,938, nodes 15
theorem unsat41s_c3_0_7_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 75,120, nodes 15
theorem unsat41s_c3_0_7_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 193,574, nodes 51
theorem unsat41s_c3_0_7_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 0, 7)` — cap-work 1,170,007 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_0_7 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_0_7_s0
  · exact unsat41s_c3_0_7_s1
  · exact unsat41s_c3_0_7_s2
  · exact unsat41s_c3_0_7_s3
  · exact unsat41s_c3_0_7_s4
  · exact unsat41s_c3_0_7_s5
  · exact unsat41s_c3_0_7_s6
  · exact unsat41s_c3_0_7_s7
  · exact unsat41s_c3_0_7_s8
  · exact unsat41s_c3_0_7_s9
  · exact unsat41s_c3_0_7_s10
  · exact unsat41s_c3_0_7_s11
  · exact unsat41s_c3_0_7_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,647, nodes 15
theorem unsat41s_c3_2_4_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 75,276, nodes 15
theorem unsat41s_c3_2_4_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,304, nodes 1
theorem unsat41s_c3_2_4_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 175,973, nodes 49
theorem unsat41s_c3_2_4_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c3_2_4_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 113,505, nodes 27
theorem unsat41s_c3_2_4_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 75,424, nodes 15
theorem unsat41s_c3_2_4_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 115,280, nodes 27
theorem unsat41s_c3_2_4_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_4_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 198,242, nodes 51
theorem unsat41s_c3_2_4_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 74,896, nodes 15
theorem unsat41s_c3_2_4_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 77,635, nodes 15
theorem unsat41s_c3_2_4_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 118,962, nodes 27
theorem unsat41s_c3_2_4_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 2, 4)` — cap-work 1,122,343 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_2_4 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_2_4_s0
  · exact unsat41s_c3_2_4_s1
  · exact unsat41s_c3_2_4_s2
  · exact unsat41s_c3_2_4_s3
  · exact unsat41s_c3_2_4_s4
  · exact unsat41s_c3_2_4_s5
  · exact unsat41s_c3_2_4_s6
  · exact unsat41s_c3_2_4_s7
  · exact unsat41s_c3_2_4_s8
  · exact unsat41s_c3_2_4_s9
  · exact unsat41s_c3_2_4_s10
  · exact unsat41s_c3_2_4_s11
  · exact unsat41s_c3_2_4_s12

end Sharp41
end EuclidsPath
