import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 16/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 14 cells ((1,2,7), (2,3,8), (3,4,6), (0,0,4), (4,6,3), (0,2,6), (4,1,5), (0,0,5), (4,6,4), (1,5,1), (2,6,2), (0,4,8), (4,3,7), (3,5,2)), 14 kernel gates,
cap-work 7,048,848 (4.0% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 2, 7)` — cap-work 519,743, nodes 95 (measured, re-verified). -/
theorem unsat41s_c1_2_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 3, 8)` — cap-work 519,743, nodes 95 (measured, re-verified). -/
theorem unsat41s_c2_3_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 4, 6)` — cap-work 517,150, nodes 105 (measured, re-verified). -/
theorem unsat41s_c3_4_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 0, 4)` — cap-work 516,679, nodes 95 (measured, re-verified). -/
theorem unsat41s_c0_0_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 6, 3)` — cap-work 516,679, nodes 95 (measured, re-verified). -/
theorem unsat41s_c4_6_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 2, 6)` — cap-work 504,351, nodes 95 (measured, re-verified). -/
theorem unsat41s_c0_2_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 1, 5)` — cap-work 504,351, nodes 95 (measured, re-verified). -/
theorem unsat41s_c4_1_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 0, 5)` — cap-work 501,927, nodes 97 (measured, re-verified). -/
theorem unsat41s_c0_0_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 6, 4)` — cap-work 501,927, nodes 97 (measured, re-verified). -/
theorem unsat41s_c4_6_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 5, 1)` — cap-work 495,333, nodes 105 (measured, re-verified). -/
theorem unsat41s_c1_5_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 6, 2)` — cap-work 495,333, nodes 105 (measured, re-verified). -/
theorem unsat41s_c2_6_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 4, 8)` — cap-work 485,725, nodes 95 (measured, re-verified). -/
theorem unsat41s_c0_4_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 3, 7)` — cap-work 485,725, nodes 95 (measured, re-verified). -/
theorem unsat41s_c4_3_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 5, 2)` — cap-work 484,182, nodes 83 (measured, re-verified). -/
theorem unsat41s_c3_5_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

end Sharp41
end EuclidsPath
