import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 01/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 5 cells ((1,6,5), (2,0,6), (3,4,10), (0,3,9), (4,2,8)), 70 kernel gates,
cap-work 6,720,904 (3.9% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,486, nodes 1
theorem unsat41s_c1_6_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 86,699, nodes 15
theorem unsat41s_c1_6_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 133,163, nodes 27
theorem unsat41s_c1_6_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 214,790, nodes 51
theorem unsat41s_c1_6_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,683, nodes 1
theorem unsat41s_c1_6_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 86,369, nodes 15
theorem unsat41s_c1_6_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 83,320, nodes 15
theorem unsat41s_c1_6_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,808, nodes 15
theorem unsat41s_c1_6_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 86,215, nodes 15
theorem unsat41s_c1_6_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,289, nodes 1
theorem unsat41s_c1_6_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,092, nodes 1
theorem unsat41s_c1_6_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 84,158, nodes 15
theorem unsat41s_c1_6_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 509,381, nodes 123
theorem unsat41s_c1_6_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 6, 5)` — cap-work 1,397,453 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_6_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_6_5_s0
  · exact unsat41s_c1_6_5_s1
  · exact unsat41s_c1_6_5_s2
  · exact unsat41s_c1_6_5_s3
  · exact unsat41s_c1_6_5_s4
  · exact unsat41s_c1_6_5_s5
  · exact unsat41s_c1_6_5_s6
  · exact unsat41s_c1_6_5_s7
  · exact unsat41s_c1_6_5_s8
  · exact unsat41s_c1_6_5_s9
  · exact unsat41s_c1_6_5_s10
  · exact unsat41s_c1_6_5_s11
  · exact unsat41s_c1_6_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 509,381, nodes 123
theorem unsat41s_c2_0_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,486, nodes 1
theorem unsat41s_c2_0_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 86,699, nodes 15
theorem unsat41s_c2_0_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 133,163, nodes 27
theorem unsat41s_c2_0_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 214,790, nodes 51
theorem unsat41s_c2_0_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,683, nodes 1
theorem unsat41s_c2_0_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 86,369, nodes 15
theorem unsat41s_c2_0_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,320, nodes 15
theorem unsat41s_c2_0_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 83,808, nodes 15
theorem unsat41s_c2_0_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 86,215, nodes 15
theorem unsat41s_c2_0_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,289, nodes 1
theorem unsat41s_c2_0_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c2_0_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 84,158, nodes 15
theorem unsat41s_c2_0_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 0, 6)` — cap-work 1,397,453 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_0_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_0_6_s0
  · exact unsat41s_c2_0_6_s1
  · exact unsat41s_c2_0_6_s2
  · exact unsat41s_c2_0_6_s3
  · exact unsat41s_c2_0_6_s4
  · exact unsat41s_c2_0_6_s5
  · exact unsat41s_c2_0_6_s6
  · exact unsat41s_c2_0_6_s7
  · exact unsat41s_c2_0_6_s8
  · exact unsat41s_c2_0_6_s9
  · exact unsat41s_c2_0_6_s10
  · exact unsat41s_c2_0_6_s11
  · exact unsat41s_c2_0_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 325,260, nodes 87
theorem unsat41s_c3_4_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 111,822, nodes 27
theorem unsat41s_c3_4_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 116,879, nodes 27
theorem unsat41s_c3_4_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 115,892, nodes 27
theorem unsat41s_c3_4_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 123,657, nodes 27
theorem unsat41s_c3_4_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 76,683, nodes 15
theorem unsat41s_c3_4_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 118,041, nodes 27
theorem unsat41s_c3_4_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 115,372, nodes 27
theorem unsat41s_c3_4_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 189,005, nodes 49
theorem unsat41s_c3_4_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,895, nodes 1
theorem unsat41s_c3_4_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 4, 10)` — cap-work 1,319,600 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_4_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_4_10_s0
  · exact unsat41s_c3_4_10_s1
  · exact unsat41s_c3_4_10_s2
  · exact unsat41s_c3_4_10_s3
  · exact unsat41s_c3_4_10_s4
  · exact unsat41s_c3_4_10_s5
  · exact unsat41s_c3_4_10_s6
  · exact unsat41s_c3_4_10_s7
  · exact unsat41s_c3_4_10_s8
  · exact unsat41s_c3_4_10_s9
  · exact unsat41s_c3_4_10_s10
  · exact unsat41s_c3_4_10_s11
  · exact unsat41s_c3_4_10_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,289, nodes 1
theorem unsat41s_c0_3_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c0_3_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 85,016, nodes 15
theorem unsat41s_c0_3_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 452,286, nodes 117
theorem unsat41s_c0_3_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,486, nodes 1
theorem unsat41s_c0_3_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 84,138, nodes 15
theorem unsat41s_c0_3_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 179,634, nodes 39
theorem unsat41s_c0_3_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 127,498, nodes 27
theorem unsat41s_c0_3_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,683, nodes 1
theorem unsat41s_c0_3_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 87,773, nodes 15
theorem unsat41s_c0_3_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,850, nodes 15
theorem unsat41s_c0_3_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 85,032, nodes 15
theorem unsat41s_c0_3_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 87,619, nodes 15
theorem unsat41s_c0_3_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 3, 9)` — cap-work 1,303,199 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_3_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_3_9_s0
  · exact unsat41s_c0_3_9_s1
  · exact unsat41s_c0_3_9_s2
  · exact unsat41s_c0_3_9_s3
  · exact unsat41s_c0_3_9_s4
  · exact unsat41s_c0_3_9_s5
  · exact unsat41s_c0_3_9_s6
  · exact unsat41s_c0_3_9_s7
  · exact unsat41s_c0_3_9_s8
  · exact unsat41s_c0_3_9_s9
  · exact unsat41s_c0_3_9_s10
  · exact unsat41s_c0_3_9_s11
  · exact unsat41s_c0_3_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,895, nodes 1
theorem unsat41s_c4_2_8_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 85,016, nodes 15
theorem unsat41s_c4_2_8_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 452,286, nodes 117
theorem unsat41s_c4_2_8_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,486, nodes 1
theorem unsat41s_c4_2_8_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 84,138, nodes 15
theorem unsat41s_c4_2_8_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 179,634, nodes 39
theorem unsat41s_c4_2_8_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 127,498, nodes 27
theorem unsat41s_c4_2_8_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,683, nodes 1
theorem unsat41s_c4_2_8_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 87,773, nodes 15
theorem unsat41s_c4_2_8_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 84,850, nodes 15
theorem unsat41s_c4_2_8_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 85,032, nodes 15
theorem unsat41s_c4_2_8_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 87,619, nodes 15
theorem unsat41s_c4_2_8_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,289, nodes 1
theorem unsat41s_c4_2_8_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 2, 8)` — cap-work 1,303,199 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_2_8 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_2_8_s0
  · exact unsat41s_c4_2_8_s1
  · exact unsat41s_c4_2_8_s2
  · exact unsat41s_c4_2_8_s3
  · exact unsat41s_c4_2_8_s4
  · exact unsat41s_c4_2_8_s5
  · exact unsat41s_c4_2_8_s6
  · exact unsat41s_c4_2_8_s7
  · exact unsat41s_c4_2_8_s8
  · exact unsat41s_c4_2_8_s9
  · exact unsat41s_c4_2_8_s10
  · exact unsat41s_c4_2_8_s11
  · exact unsat41s_c4_2_8_s12

end Sharp41
end EuclidsPath
