import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 04/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 7 cells ((4,0,10), (0,3,2), (4,2,1), (0,4,6), (4,3,5), (0,2,9), (1,3,10)), 98 kernel gates,
cap-work 6,611,947 (3.8% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 83,486, nodes 15
theorem unsat41s_c4_0_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c4_0_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c4_0_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,289, nodes 1
theorem unsat41s_c4_0_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,486, nodes 1
theorem unsat41s_c4_0_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 82,329, nodes 15
theorem unsat41s_c4_0_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 130,563, nodes 27
theorem unsat41s_c4_0_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,289, nodes 1
theorem unsat41s_c4_0_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,486, nodes 1
theorem unsat41s_c4_0_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 438,688, nodes 109
theorem unsat41s_c4_0_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,694, nodes 15
theorem unsat41s_c4_0_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c4_0_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 86,357, nodes 15
theorem unsat41s_c4_0_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 0, 10)` — cap-work 956,943 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_0_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_0_10_s0
  · exact unsat41s_c4_0_10_s1
  · exact unsat41s_c4_0_10_s2
  · exact unsat41s_c4_0_10_s3
  · exact unsat41s_c4_0_10_s4
  · exact unsat41s_c4_0_10_s5
  · exact unsat41s_c4_0_10_s6
  · exact unsat41s_c4_0_10_s7
  · exact unsat41s_c4_0_10_s8
  · exact unsat41s_c4_0_10_s9
  · exact unsat41s_c4_0_10_s10
  · exact unsat41s_c4_0_10_s11
  · exact unsat41s_c4_0_10_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,486, nodes 1
theorem unsat41s_c0_3_2_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c0_3_2_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 82,649, nodes 15
theorem unsat41s_c0_3_2_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 230,645, nodes 51
theorem unsat41s_c0_3_2_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,683, nodes 1
theorem unsat41s_c0_3_2_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 130,031, nodes 27
theorem unsat41s_c0_3_2_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 82,145, nodes 15
theorem unsat41s_c0_3_2_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,289, nodes 1
theorem unsat41s_c0_3_2_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,486, nodes 1
theorem unsat41s_c0_3_2_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 84,884, nodes 15
theorem unsat41s_c0_3_2_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,526, nodes 15
theorem unsat41s_c0_3_2_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 130,184, nodes 27
theorem unsat41s_c0_3_2_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 84,872, nodes 15
theorem unsat41s_c0_3_2_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 3, 2)` — cap-work 946,972 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_3_2 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_3_2_s0
  · exact unsat41s_c0_3_2_s1
  · exact unsat41s_c0_3_2_s2
  · exact unsat41s_c0_3_2_s3
  · exact unsat41s_c0_3_2_s4
  · exact unsat41s_c0_3_2_s5
  · exact unsat41s_c0_3_2_s6
  · exact unsat41s_c0_3_2_s7
  · exact unsat41s_c0_3_2_s8
  · exact unsat41s_c0_3_2_s9
  · exact unsat41s_c0_3_2_s10
  · exact unsat41s_c0_3_2_s11
  · exact unsat41s_c0_3_2_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,092, nodes 1
theorem unsat41s_c4_2_1_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 82,649, nodes 15
theorem unsat41s_c4_2_1_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 230,645, nodes 51
theorem unsat41s_c4_2_1_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,683, nodes 1
theorem unsat41s_c4_2_1_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 130,031, nodes 27
theorem unsat41s_c4_2_1_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 82,145, nodes 15
theorem unsat41s_c4_2_1_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,289, nodes 1
theorem unsat41s_c4_2_1_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,486, nodes 1
theorem unsat41s_c4_2_1_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 84,884, nodes 15
theorem unsat41s_c4_2_1_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 84,526, nodes 15
theorem unsat41s_c4_2_1_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 130,184, nodes 27
theorem unsat41s_c4_2_1_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 84,872, nodes 15
theorem unsat41s_c4_2_1_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,486, nodes 1
theorem unsat41s_c4_2_1_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 2, 1)` — cap-work 946,972 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_2_1 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_2_1_s0
  · exact unsat41s_c4_2_1_s1
  · exact unsat41s_c4_2_1_s2
  · exact unsat41s_c4_2_1_s3
  · exact unsat41s_c4_2_1_s4
  · exact unsat41s_c4_2_1_s5
  · exact unsat41s_c4_2_1_s6
  · exact unsat41s_c4_2_1_s7
  · exact unsat41s_c4_2_1_s8
  · exact unsat41s_c4_2_1_s9
  · exact unsat41s_c4_2_1_s10
  · exact unsat41s_c4_2_1_s11
  · exact unsat41s_c4_2_1_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,635, nodes 15
theorem unsat41s_c0_4_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 77,053, nodes 15
theorem unsat41s_c0_4_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c0_4_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 77,543, nodes 15
theorem unsat41s_c0_4_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,304, nodes 1
theorem unsat41s_c0_4_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 160,763, nodes 39
theorem unsat41s_c0_4_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c0_4_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 117,886, nodes 27
theorem unsat41s_c0_4_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 117,666, nodes 27
theorem unsat41s_c0_4_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c0_4_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 163,352, nodes 39
theorem unsat41s_c0_4_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 117,947, nodes 27
theorem unsat41s_c0_4_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 4, 6)` — cap-work 942,941 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_4_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_4_6_s0
  · exact unsat41s_c0_4_6_s1
  · exact unsat41s_c0_4_6_s2
  · exact unsat41s_c0_4_6_s3
  · exact unsat41s_c0_4_6_s4
  · exact unsat41s_c0_4_6_s5
  · exact unsat41s_c0_4_6_s6
  · exact unsat41s_c0_4_6_s7
  · exact unsat41s_c0_4_6_s8
  · exact unsat41s_c0_4_6_s9
  · exact unsat41s_c0_4_6_s10
  · exact unsat41s_c0_4_6_s11
  · exact unsat41s_c0_4_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,053, nodes 15
theorem unsat41s_c4_3_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c4_3_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 77,543, nodes 15
theorem unsat41s_c4_3_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,304, nodes 1
theorem unsat41s_c4_3_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 160,763, nodes 39
theorem unsat41s_c4_3_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,895, nodes 1
theorem unsat41s_c4_3_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 117,886, nodes 27
theorem unsat41s_c4_3_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 117,666, nodes 27
theorem unsat41s_c4_3_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c4_3_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c4_3_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 163,352, nodes 39
theorem unsat41s_c4_3_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 117,947, nodes 27
theorem unsat41s_c4_3_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 77,635, nodes 15
theorem unsat41s_c4_3_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 3, 5)` — cap-work 942,941 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_3_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_3_5_s0
  · exact unsat41s_c4_3_5_s1
  · exact unsat41s_c4_3_5_s2
  · exact unsat41s_c4_3_5_s3
  · exact unsat41s_c4_3_5_s4
  · exact unsat41s_c4_3_5_s5
  · exact unsat41s_c4_3_5_s6
  · exact unsat41s_c4_3_5_s7
  · exact unsat41s_c4_3_5_s8
  · exact unsat41s_c4_3_5_s9
  · exact unsat41s_c4_3_5_s10
  · exact unsat41s_c4_3_5_s11
  · exact unsat41s_c4_3_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 75,120, nodes 15
theorem unsat41s_c0_2_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 114,537, nodes 27
theorem unsat41s_c0_2_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c0_2_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 117,666, nodes 27
theorem unsat41s_c0_2_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,304, nodes 1
theorem unsat41s_c0_2_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 76,595, nodes 15
theorem unsat41s_c0_2_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 79,158, nodes 15
theorem unsat41s_c0_2_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 78,984, nodes 15
theorem unsat41s_c0_2_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 163,762, nodes 39
theorem unsat41s_c0_2_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 198,868, nodes 51
theorem unsat41s_c0_2_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 2, 9)` — cap-work 937,589 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_2_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_2_9_s0
  · exact unsat41s_c0_2_9_s1
  · exact unsat41s_c0_2_9_s2
  · exact unsat41s_c0_2_9_s3
  · exact unsat41s_c0_2_9_s4
  · exact unsat41s_c0_2_9_s5
  · exact unsat41s_c0_2_9_s6
  · exact unsat41s_c0_2_9_s7
  · exact unsat41s_c0_2_9_s8
  · exact unsat41s_c0_2_9_s9
  · exact unsat41s_c0_2_9_s10
  · exact unsat41s_c0_2_9_s11
  · exact unsat41s_c0_2_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c1_3_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 75,120, nodes 15
theorem unsat41s_c1_3_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 114,537, nodes 27
theorem unsat41s_c1_3_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c1_3_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 117,666, nodes 27
theorem unsat41s_c1_3_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,304, nodes 1
theorem unsat41s_c1_3_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 76,595, nodes 15
theorem unsat41s_c1_3_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 79,158, nodes 15
theorem unsat41s_c1_3_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c1_3_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 78,984, nodes 15
theorem unsat41s_c1_3_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 163,762, nodes 39
theorem unsat41s_c1_3_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 198,868, nodes 51
theorem unsat41s_c1_3_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,698, nodes 1
theorem unsat41s_c1_3_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 3, 10)` — cap-work 937,589 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_3_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_3_10_s0
  · exact unsat41s_c1_3_10_s1
  · exact unsat41s_c1_3_10_s2
  · exact unsat41s_c1_3_10_s3
  · exact unsat41s_c1_3_10_s4
  · exact unsat41s_c1_3_10_s5
  · exact unsat41s_c1_3_10_s6
  · exact unsat41s_c1_3_10_s7
  · exact unsat41s_c1_3_10_s8
  · exact unsat41s_c1_3_10_s9
  · exact unsat41s_c1_3_10_s10
  · exact unsat41s_c1_3_10_s11
  · exact unsat41s_c1_3_10_s12

end Sharp41
end EuclidsPath
