import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 22/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 29 cells ((1,3,5), (2,4,6), (3,2,1), (1,1,7), (2,2,8), (0,1,4), (4,0,3), (1,4,0), (2,5,1), (0,3,3), (3,1,1), (4,2,2), (1,6,8), (2,0,9), (3,1,10), (1,1,1), (2,2,2), (3,3,3), (0,1,10), (3,6,8), (4,0,9), (1,6,10), (2,0,0), (3,5,4), (0,0,6), (4,6,5), (0,3,1), (4,2,0), (1,2,5)), 29 kernel gates,
cap-work 7,374,279 (4.2% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 3, 5)` — cap-work 277,071, nodes 53 (measured, re-verified). -/
theorem unsat41s_c1_3_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 4, 6)` — cap-work 277,071, nodes 53 (measured, re-verified). -/
theorem unsat41s_c2_4_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 2, 1)` — cap-work 260,779, nodes 59 (measured, re-verified). -/
theorem unsat41s_c3_2_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 1, 7)` — cap-work 256,343, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_1_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 2, 8)` — cap-work 256,343, nodes 41 (measured, re-verified). -/
theorem unsat41s_c2_2_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 1, 4)` — cap-work 255,689, nodes 41 (measured, re-verified). -/
theorem unsat41s_c0_1_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 0, 3)` — cap-work 255,689, nodes 41 (measured, re-verified). -/
theorem unsat41s_c4_0_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 4, 0)` — cap-work 255,351, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_4_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 5, 1)` — cap-work 255,351, nodes 41 (measured, re-verified). -/
theorem unsat41s_c2_5_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 3, 3)` — cap-work 253,781, nodes 41 (measured, re-verified). -/
theorem unsat41s_c0_3_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 1, 1)` — cap-work 253,781, nodes 41 (measured, re-verified). -/
theorem unsat41s_c3_1_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 2, 2)` — cap-work 253,781, nodes 41 (measured, re-verified). -/
theorem unsat41s_c4_2_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 6, 8)` — cap-work 253,475, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_6_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 0, 9)` — cap-work 253,475, nodes 41 (measured, re-verified). -/
theorem unsat41s_c2_0_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 1, 10)` — cap-work 253,475, nodes 41 (measured, re-verified). -/
theorem unsat41s_c3_1_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 1, 1)` — cap-work 251,316, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_1_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 2, 2)` — cap-work 251,316, nodes 41 (measured, re-verified). -/
theorem unsat41s_c2_2_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 3, 3)` — cap-work 251,316, nodes 41 (measured, re-verified). -/
theorem unsat41s_c3_3_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 1, 10)` — cap-work 250,836, nodes 41 (measured, re-verified). -/
theorem unsat41s_c0_1_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 6, 8)` — cap-work 250,836, nodes 41 (measured, re-verified). -/
theorem unsat41s_c3_6_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 6 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 0, 9)` — cap-work 250,836, nodes 41 (measured, re-verified). -/
theorem unsat41s_c4_0_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 6, 10)` — cap-work 250,764, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_6_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 0, 0)` — cap-work 250,764, nodes 41 (measured, re-verified). -/
theorem unsat41s_c2_0_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 5, 4)` — cap-work 249,462, nodes 41 (measured, re-verified). -/
theorem unsat41s_c3_5_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 0, 6)` — cap-work 249,348, nodes 41 (measured, re-verified). -/
theorem unsat41s_c0_0_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 6, 5)` — cap-work 249,348, nodes 41 (measured, re-verified). -/
theorem unsat41s_c4_6_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 3, 1)` — cap-work 248,944, nodes 41 (measured, re-verified). -/
theorem unsat41s_c0_3_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 2, 0)` — cap-work 248,944, nodes 41 (measured, re-verified). -/
theorem unsat41s_c4_2_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 2, 5)` — cap-work 248,794, nodes 41 (measured, re-verified). -/
theorem unsat41s_c1_2_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

end Sharp41
end EuclidsPath
