import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 13/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 11 cells ((2,2,1), (0,4,10), (4,3,9), (0,5,1), (4,4,0), (1,2,6), (2,3,7), (0,4,4), (1,0,0), (2,1,1), (3,2,2)), 154 kernel gates,
cap-work 6,931,134 (4.0% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,486, nodes 1
theorem unsat41s_c2_2_1_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,289, nodes 1
theorem unsat41s_c2_2_1_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c2_2_1_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c2_2_1_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 83,906, nodes 15
theorem unsat41s_c2_2_1_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 85,879, nodes 15
theorem unsat41s_c2_2_1_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c2_2_1_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,810, nodes 15
theorem unsat41s_c2_2_1_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 171,820, nodes 39
theorem unsat41s_c2_2_1_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,486, nodes 1
theorem unsat41s_c2_2_1_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,289, nodes 1
theorem unsat41s_c2_2_1_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 84,154, nodes 15
theorem unsat41s_c2_2_1_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 81,775, nodes 15
theorem unsat41s_c2_2_1_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 2, 1)` — cap-work 642,170 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_2_1 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_2_1_s0
  · exact unsat41s_c2_2_1_s1
  · exact unsat41s_c2_2_1_s2
  · exact unsat41s_c2_2_1_s3
  · exact unsat41s_c2_2_1_s4
  · exact unsat41s_c2_2_1_s5
  · exact unsat41s_c2_2_1_s6
  · exact unsat41s_c2_2_1_s7
  · exact unsat41s_c2_2_1_s8
  · exact unsat41s_c2_2_1_s9
  · exact unsat41s_c2_2_1_s10
  · exact unsat41s_c2_2_1_s11
  · exact unsat41s_c2_2_1_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c0_4_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c0_4_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,304, nodes 1
theorem unsat41s_c0_4_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c0_4_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 247,903, nodes 63
theorem unsat41s_c0_4_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,895, nodes 1
theorem unsat41s_c0_4_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 76,513, nodes 15
theorem unsat41s_c0_4_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,895, nodes 1
theorem unsat41s_c0_4_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 169,548, nodes 39
theorem unsat41s_c0_4_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 79,420, nodes 15
theorem unsat41s_c0_4_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 4, 10)` — cap-work 633,863 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_4_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_4_10_s0
  · exact unsat41s_c0_4_10_s1
  · exact unsat41s_c0_4_10_s2
  · exact unsat41s_c0_4_10_s3
  · exact unsat41s_c0_4_10_s4
  · exact unsat41s_c0_4_10_s5
  · exact unsat41s_c0_4_10_s6
  · exact unsat41s_c0_4_10_s7
  · exact unsat41s_c0_4_10_s8
  · exact unsat41s_c0_4_10_s9
  · exact unsat41s_c0_4_10_s10
  · exact unsat41s_c0_4_10_s11
  · exact unsat41s_c0_4_10_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,698, nodes 1
theorem unsat41s_c4_3_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c4_3_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,304, nodes 1
theorem unsat41s_c4_3_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,501, nodes 1
theorem unsat41s_c4_3_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,501, nodes 1
theorem unsat41s_c4_3_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c4_3_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 247,903, nodes 63
theorem unsat41s_c4_3_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,895, nodes 1
theorem unsat41s_c4_3_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 76,513, nodes 15
theorem unsat41s_c4_3_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,895, nodes 1
theorem unsat41s_c4_3_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 169,548, nodes 39
theorem unsat41s_c4_3_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 79,420, nodes 15
theorem unsat41s_c4_3_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c4_3_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 3, 9)` — cap-work 633,863 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_3_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_3_9_s0
  · exact unsat41s_c4_3_9_s1
  · exact unsat41s_c4_3_9_s2
  · exact unsat41s_c4_3_9_s3
  · exact unsat41s_c4_3_9_s4
  · exact unsat41s_c4_3_9_s5
  · exact unsat41s_c4_3_9_s6
  · exact unsat41s_c4_3_9_s7
  · exact unsat41s_c4_3_9_s8
  · exact unsat41s_c4_3_9_s9
  · exact unsat41s_c4_3_9_s10
  · exact unsat41s_c4_3_9_s11
  · exact unsat41s_c4_3_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 170,708, nodes 39
theorem unsat41s_c0_5_1_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 81,897, nodes 15
theorem unsat41s_c0_5_1_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c0_5_1_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c0_5_1_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,092, nodes 1
theorem unsat41s_c0_5_1_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 82,235, nodes 15
theorem unsat41s_c0_5_1_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 82,085, nodes 15
theorem unsat41s_c0_5_1_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,092, nodes 1
theorem unsat41s_c0_5_1_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,486, nodes 1
theorem unsat41s_c0_5_1_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c0_5_1_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 82,075, nodes 15
theorem unsat41s_c0_5_1_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 84,470, nodes 15
theorem unsat41s_c0_5_1_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,289, nodes 1
theorem unsat41s_c0_5_1_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 5, 1)` — cap-work 633,114 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_5_1 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_5_1_s0
  · exact unsat41s_c0_5_1_s1
  · exact unsat41s_c0_5_1_s2
  · exact unsat41s_c0_5_1_s3
  · exact unsat41s_c0_5_1_s4
  · exact unsat41s_c0_5_1_s5
  · exact unsat41s_c0_5_1_s6
  · exact unsat41s_c0_5_1_s7
  · exact unsat41s_c0_5_1_s8
  · exact unsat41s_c0_5_1_s9
  · exact unsat41s_c0_5_1_s10
  · exact unsat41s_c0_5_1_s11
  · exact unsat41s_c0_5_1_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 81,897, nodes 15
theorem unsat41s_c4_4_0_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c4_4_0_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c4_4_0_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c4_4_0_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 82,235, nodes 15
theorem unsat41s_c4_4_0_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 82,085, nodes 15
theorem unsat41s_c4_4_0_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c4_4_0_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,486, nodes 1
theorem unsat41s_c4_4_0_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c4_4_0_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 82,075, nodes 15
theorem unsat41s_c4_4_0_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,470, nodes 15
theorem unsat41s_c4_4_0_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,289, nodes 1
theorem unsat41s_c4_4_0_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 170,708, nodes 39
theorem unsat41s_c4_4_0_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 4, 0)` — cap-work 633,114 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_4_0 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_4_0_s0
  · exact unsat41s_c4_4_0_s1
  · exact unsat41s_c4_4_0_s2
  · exact unsat41s_c4_4_0_s3
  · exact unsat41s_c4_4_0_s4
  · exact unsat41s_c4_4_0_s5
  · exact unsat41s_c4_4_0_s6
  · exact unsat41s_c4_4_0_s7
  · exact unsat41s_c4_4_0_s8
  · exact unsat41s_c4_4_0_s9
  · exact unsat41s_c4_4_0_s10
  · exact unsat41s_c4_4_0_s11
  · exact unsat41s_c4_4_0_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 74,282, nodes 15
theorem unsat41s_c1_2_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c1_2_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,501, nodes 1
theorem unsat41s_c1_2_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 74,626, nodes 15
theorem unsat41s_c1_2_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,304, nodes 1
theorem unsat41s_c1_2_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 77,505, nodes 15
theorem unsat41s_c1_2_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 77,169, nodes 15
theorem unsat41s_c1_2_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 77,357, nodes 15
theorem unsat41s_c1_2_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 204,470, nodes 51
theorem unsat41s_c1_2_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,501, nodes 1
theorem unsat41s_c1_2_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c1_2_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 2, 6)` — cap-work 631,507 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_2_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_2_6_s0
  · exact unsat41s_c1_2_6_s1
  · exact unsat41s_c1_2_6_s2
  · exact unsat41s_c1_2_6_s3
  · exact unsat41s_c1_2_6_s4
  · exact unsat41s_c1_2_6_s5
  · exact unsat41s_c1_2_6_s6
  · exact unsat41s_c1_2_6_s7
  · exact unsat41s_c1_2_6_s8
  · exact unsat41s_c1_2_6_s9
  · exact unsat41s_c1_2_6_s10
  · exact unsat41s_c1_2_6_s11
  · exact unsat41s_c1_2_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c2_3_7_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 74,282, nodes 15
theorem unsat41s_c2_3_7_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c2_3_7_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,501, nodes 1
theorem unsat41s_c2_3_7_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 74,626, nodes 15
theorem unsat41s_c2_3_7_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,304, nodes 1
theorem unsat41s_c2_3_7_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 77,505, nodes 15
theorem unsat41s_c2_3_7_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_7_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 77,169, nodes 15
theorem unsat41s_c2_3_7_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 77,357, nodes 15
theorem unsat41s_c2_3_7_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 204,470, nodes 51
theorem unsat41s_c2_3_7_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_7_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c2_3_7_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 3, 7)` — cap-work 631,507 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_3_7 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_3_7_s0
  · exact unsat41s_c2_3_7_s1
  · exact unsat41s_c2_3_7_s2
  · exact unsat41s_c2_3_7_s3
  · exact unsat41s_c2_3_7_s4
  · exact unsat41s_c2_3_7_s5
  · exact unsat41s_c2_3_7_s6
  · exact unsat41s_c2_3_7_s7
  · exact unsat41s_c2_3_7_s8
  · exact unsat41s_c2_3_7_s9
  · exact unsat41s_c2_3_7_s10
  · exact unsat41s_c2_3_7_s11
  · exact unsat41s_c2_3_7_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_4_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_4_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c0_4_4_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 77,353, nodes 15
theorem unsat41s_c0_4_4_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 77,177, nodes 15
theorem unsat41s_c0_4_4_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 194,227, nodes 51
theorem unsat41s_c0_4_4_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c0_4_4_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,501, nodes 1
theorem unsat41s_c0_4_4_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 76,999, nodes 15
theorem unsat41s_c0_4_4_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 73,690, nodes 15
theorem unsat41s_c0_4_4_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,895, nodes 1
theorem unsat41s_c0_4_4_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 77,455, nodes 15
theorem unsat41s_c0_4_4_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,304, nodes 1
theorem unsat41s_c0_4_4_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 4, 4)` — cap-work 622,999 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_4_4 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_4_4_s0
  · exact unsat41s_c0_4_4_s1
  · exact unsat41s_c0_4_4_s2
  · exact unsat41s_c0_4_4_s3
  · exact unsat41s_c0_4_4_s4
  · exact unsat41s_c0_4_4_s5
  · exact unsat41s_c0_4_4_s6
  · exact unsat41s_c0_4_4_s7
  · exact unsat41s_c0_4_4_s8
  · exact unsat41s_c0_4_4_s9
  · exact unsat41s_c0_4_4_s10
  · exact unsat41s_c0_4_4_s11
  · exact unsat41s_c0_4_4_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,177, nodes 15
theorem unsat41s_c1_0_0_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 194,227, nodes 51
theorem unsat41s_c1_0_0_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_0_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_0_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 76,999, nodes 15
theorem unsat41s_c1_0_0_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 73,690, nodes 15
theorem unsat41s_c1_0_0_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c1_0_0_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 77,455, nodes 15
theorem unsat41s_c1_0_0_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,304, nodes 1
theorem unsat41s_c1_0_0_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_0_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_0_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_0_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 77,353, nodes 15
theorem unsat41s_c1_0_0_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 0, 0)` — cap-work 622,999 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_0_0 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_0_0_s0
  · exact unsat41s_c1_0_0_s1
  · exact unsat41s_c1_0_0_s2
  · exact unsat41s_c1_0_0_s3
  · exact unsat41s_c1_0_0_s4
  · exact unsat41s_c1_0_0_s5
  · exact unsat41s_c1_0_0_s6
  · exact unsat41s_c1_0_0_s7
  · exact unsat41s_c1_0_0_s8
  · exact unsat41s_c1_0_0_s9
  · exact unsat41s_c1_0_0_s10
  · exact unsat41s_c1_0_0_s11
  · exact unsat41s_c1_0_0_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,353, nodes 15
theorem unsat41s_c2_1_1_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 77,177, nodes 15
theorem unsat41s_c2_1_1_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 194,227, nodes 51
theorem unsat41s_c2_1_1_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_1_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_1_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 76,999, nodes 15
theorem unsat41s_c2_1_1_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 73,690, nodes 15
theorem unsat41s_c2_1_1_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,895, nodes 1
theorem unsat41s_c2_1_1_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 77,455, nodes 15
theorem unsat41s_c2_1_1_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,304, nodes 1
theorem unsat41s_c2_1_1_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_1_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_1_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_1_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 1, 1)` — cap-work 622,999 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_1_1 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_1_1_s0
  · exact unsat41s_c2_1_1_s1
  · exact unsat41s_c2_1_1_s2
  · exact unsat41s_c2_1_1_s3
  · exact unsat41s_c2_1_1_s4
  · exact unsat41s_c2_1_1_s5
  · exact unsat41s_c2_1_1_s6
  · exact unsat41s_c2_1_1_s7
  · exact unsat41s_c2_1_1_s8
  · exact unsat41s_c2_1_1_s9
  · exact unsat41s_c2_1_1_s10
  · exact unsat41s_c2_1_1_s11
  · exact unsat41s_c2_1_1_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,698, nodes 1
theorem unsat41s_c3_2_2_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 77,353, nodes 15
theorem unsat41s_c3_2_2_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 77,177, nodes 15
theorem unsat41s_c3_2_2_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 194,227, nodes 51
theorem unsat41s_c3_2_2_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c3_2_2_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_2_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 76,999, nodes 15
theorem unsat41s_c3_2_2_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 73,690, nodes 15
theorem unsat41s_c3_2_2_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,895, nodes 1
theorem unsat41s_c3_2_2_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 77,455, nodes 15
theorem unsat41s_c3_2_2_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,304, nodes 1
theorem unsat41s_c3_2_2_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_2_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_2_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 2, 2)` — cap-work 622,999 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_2_2 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_2_2_s0
  · exact unsat41s_c3_2_2_s1
  · exact unsat41s_c3_2_2_s2
  · exact unsat41s_c3_2_2_s3
  · exact unsat41s_c3_2_2_s4
  · exact unsat41s_c3_2_2_s5
  · exact unsat41s_c3_2_2_s6
  · exact unsat41s_c3_2_2_s7
  · exact unsat41s_c3_2_2_s8
  · exact unsat41s_c3_2_2_s9
  · exact unsat41s_c3_2_2_s10
  · exact unsat41s_c3_2_2_s11
  · exact unsat41s_c3_2_2_s12

end Sharp41
end EuclidsPath
