import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 10/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 10 cells ((2,2,5), (1,2,4), (2,3,5), (1,4,10), (2,5,0), (1,5,5), (2,6,6), (0,2,7), (4,1,6), (0,2,0)), 140 kernel gates,
cap-work 7,219,694 (4.1% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,895, nodes 1
theorem unsat41s_c2_2_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c2_2_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 82,619, nodes 15
theorem unsat41s_c2_2_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 80,724, nodes 15
theorem unsat41s_c2_2_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 76,745, nodes 15
theorem unsat41s_c2_2_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c2_2_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c2_2_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 77,483, nodes 15
theorem unsat41s_c2_2_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 124,349, nodes 27
theorem unsat41s_c2_2_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,289, nodes 1
theorem unsat41s_c2_2_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 175,344, nodes 39
theorem unsat41s_c2_2_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 80,044, nodes 15
theorem unsat41s_c2_2_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,895, nodes 1
theorem unsat41s_c2_2_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 2, 5)` — cap-work 739,269 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_2_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_2_5_s0
  · exact unsat41s_c2_2_5_s1
  · exact unsat41s_c2_2_5_s2
  · exact unsat41s_c2_2_5_s3
  · exact unsat41s_c2_2_5_s4
  · exact unsat41s_c2_2_5_s5
  · exact unsat41s_c2_2_5_s6
  · exact unsat41s_c2_2_5_s7
  · exact unsat41s_c2_2_5_s8
  · exact unsat41s_c2_2_5_s9
  · exact unsat41s_c2_2_5_s10
  · exact unsat41s_c2_2_5_s11
  · exact unsat41s_c2_2_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 76,169, nodes 15
theorem unsat41s_c1_2_4_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,289, nodes 1
theorem unsat41s_c1_2_4_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c1_2_4_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 79,058, nodes 15
theorem unsat41s_c1_2_4_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 123,117, nodes 27
theorem unsat41s_c1_2_4_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c1_2_4_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c1_2_4_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_4_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c1_2_4_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 242,327, nodes 61
theorem unsat41s_c1_2_4_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,092, nodes 1
theorem unsat41s_c1_2_4_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 80,785, nodes 15
theorem unsat41s_c1_2_4_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 79,252, nodes 15
theorem unsat41s_c1_2_4_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 2, 4)` — cap-work 729,367 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_2_4 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_2_4_s0
  · exact unsat41s_c1_2_4_s1
  · exact unsat41s_c1_2_4_s2
  · exact unsat41s_c1_2_4_s3
  · exact unsat41s_c1_2_4_s4
  · exact unsat41s_c1_2_4_s5
  · exact unsat41s_c1_2_4_s6
  · exact unsat41s_c1_2_4_s7
  · exact unsat41s_c1_2_4_s8
  · exact unsat41s_c1_2_4_s9
  · exact unsat41s_c1_2_4_s10
  · exact unsat41s_c1_2_4_s11
  · exact unsat41s_c1_2_4_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 79,252, nodes 15
theorem unsat41s_c2_3_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 76,169, nodes 15
theorem unsat41s_c2_3_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,289, nodes 1
theorem unsat41s_c2_3_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c2_3_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 79,058, nodes 15
theorem unsat41s_c2_3_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 123,117, nodes 27
theorem unsat41s_c2_3_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c2_3_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,895, nodes 1
theorem unsat41s_c2_3_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c2_3_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 242,327, nodes 61
theorem unsat41s_c2_3_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c2_3_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 80,785, nodes 15
theorem unsat41s_c2_3_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 3, 5)` — cap-work 729,367 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_3_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_3_5_s0
  · exact unsat41s_c2_3_5_s1
  · exact unsat41s_c2_3_5_s2
  · exact unsat41s_c2_3_5_s3
  · exact unsat41s_c2_3_5_s4
  · exact unsat41s_c2_3_5_s5
  · exact unsat41s_c2_3_5_s6
  · exact unsat41s_c2_3_5_s7
  · exact unsat41s_c2_3_5_s8
  · exact unsat41s_c2_3_5_s9
  · exact unsat41s_c2_3_5_s10
  · exact unsat41s_c2_3_5_s11
  · exact unsat41s_c2_3_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,092, nodes 1
theorem unsat41s_c1_4_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c1_4_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c1_4_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 82,455, nodes 15
theorem unsat41s_c1_4_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 265,841, nodes 71
theorem unsat41s_c1_4_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,289, nodes 1
theorem unsat41s_c1_4_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 84,138, nodes 15
theorem unsat41s_c1_4_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 82,295, nodes 15
theorem unsat41s_c1_4_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c1_4_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,486, nodes 1
theorem unsat41s_c1_4_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,092, nodes 1
theorem unsat41s_c1_4_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 82,289, nodes 15
theorem unsat41s_c1_4_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 82,471, nodes 15
theorem unsat41s_c1_4_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 4, 10)` — cap-work 729,133 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_4_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_4_10_s0
  · exact unsat41s_c1_4_10_s1
  · exact unsat41s_c1_4_10_s2
  · exact unsat41s_c1_4_10_s3
  · exact unsat41s_c1_4_10_s4
  · exact unsat41s_c1_4_10_s5
  · exact unsat41s_c1_4_10_s6
  · exact unsat41s_c1_4_10_s7
  · exact unsat41s_c1_4_10_s8
  · exact unsat41s_c1_4_10_s9
  · exact unsat41s_c1_4_10_s10
  · exact unsat41s_c1_4_10_s11
  · exact unsat41s_c1_4_10_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 82,471, nodes 15
theorem unsat41s_c2_5_0_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c2_5_0_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c2_5_0_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c2_5_0_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 82,455, nodes 15
theorem unsat41s_c2_5_0_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 265,841, nodes 71
theorem unsat41s_c2_5_0_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,289, nodes 1
theorem unsat41s_c2_5_0_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 84,138, nodes 15
theorem unsat41s_c2_5_0_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 82,295, nodes 15
theorem unsat41s_c2_5_0_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c2_5_0_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,486, nodes 1
theorem unsat41s_c2_5_0_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c2_5_0_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 82,289, nodes 15
theorem unsat41s_c2_5_0_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 5, 0)` — cap-work 729,133 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_5_0 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_5_0_s0
  · exact unsat41s_c2_5_0_s1
  · exact unsat41s_c2_5_0_s2
  · exact unsat41s_c2_5_0_s3
  · exact unsat41s_c2_5_0_s4
  · exact unsat41s_c2_5_0_s5
  · exact unsat41s_c2_5_0_s6
  · exact unsat41s_c2_5_0_s7
  · exact unsat41s_c2_5_0_s8
  · exact unsat41s_c2_5_0_s9
  · exact unsat41s_c2_5_0_s10
  · exact unsat41s_c2_5_0_s11
  · exact unsat41s_c2_5_0_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,304, nodes 1
theorem unsat41s_c1_5_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 77,163, nodes 15
theorem unsat41s_c1_5_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c1_5_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 77,011, nodes 15
theorem unsat41s_c1_5_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 76,481, nodes 15
theorem unsat41s_c1_5_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 76,987, nodes 15
theorem unsat41s_c1_5_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 156,463, nodes 39
theorem unsat41s_c1_5_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,698, nodes 1
theorem unsat41s_c1_5_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c1_5_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 77,681, nodes 15
theorem unsat41s_c1_5_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 74,456, nodes 15
theorem unsat41s_c1_5_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c1_5_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 75,074, nodes 15
theorem unsat41s_c1_5_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 5, 5)` — cap-work 724,412 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_5_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_5_5_s0
  · exact unsat41s_c1_5_5_s1
  · exact unsat41s_c1_5_5_s2
  · exact unsat41s_c1_5_5_s3
  · exact unsat41s_c1_5_5_s4
  · exact unsat41s_c1_5_5_s5
  · exact unsat41s_c1_5_5_s6
  · exact unsat41s_c1_5_5_s7
  · exact unsat41s_c1_5_5_s8
  · exact unsat41s_c1_5_5_s9
  · exact unsat41s_c1_5_5_s10
  · exact unsat41s_c1_5_5_s11
  · exact unsat41s_c1_5_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 75,074, nodes 15
theorem unsat41s_c2_6_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,304, nodes 1
theorem unsat41s_c2_6_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 77,163, nodes 15
theorem unsat41s_c2_6_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c2_6_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 77,011, nodes 15
theorem unsat41s_c2_6_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 76,481, nodes 15
theorem unsat41s_c2_6_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 76,987, nodes 15
theorem unsat41s_c2_6_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 156,463, nodes 39
theorem unsat41s_c2_6_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c2_6_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c2_6_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 77,681, nodes 15
theorem unsat41s_c2_6_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 74,456, nodes 15
theorem unsat41s_c2_6_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,895, nodes 1
theorem unsat41s_c2_6_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 6, 6)` — cap-work 724,412 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_6_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_6_6_s0
  · exact unsat41s_c2_6_6_s1
  · exact unsat41s_c2_6_6_s2
  · exact unsat41s_c2_6_6_s3
  · exact unsat41s_c2_6_6_s4
  · exact unsat41s_c2_6_6_s5
  · exact unsat41s_c2_6_6_s6
  · exact unsat41s_c2_6_6_s7
  · exact unsat41s_c2_6_6_s8
  · exact unsat41s_c2_6_6_s9
  · exact unsat41s_c2_6_6_s10
  · exact unsat41s_c2_6_6_s11
  · exact unsat41s_c2_6_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 78,710, nodes 15
theorem unsat41s_c0_2_7_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 197,672, nodes 51
theorem unsat41s_c0_2_7_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c0_2_7_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_7_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_7_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 76,615, nodes 15
theorem unsat41s_c0_2_7_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c0_2_7_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 79,188, nodes 15
theorem unsat41s_c0_2_7_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 78,840, nodes 15
theorem unsat41s_c0_2_7_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_7_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 76,815, nodes 15
theorem unsat41s_c0_2_7_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_7_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 79,514, nodes 15
theorem unsat41s_c0_2_7_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 2, 7)` — cap-work 707,936 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_2_7 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_2_7_s0
  · exact unsat41s_c0_2_7_s1
  · exact unsat41s_c0_2_7_s2
  · exact unsat41s_c0_2_7_s3
  · exact unsat41s_c0_2_7_s4
  · exact unsat41s_c0_2_7_s5
  · exact unsat41s_c0_2_7_s6
  · exact unsat41s_c0_2_7_s7
  · exact unsat41s_c0_2_7_s8
  · exact unsat41s_c0_2_7_s9
  · exact unsat41s_c0_2_7_s10
  · exact unsat41s_c0_2_7_s11
  · exact unsat41s_c0_2_7_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 197,672, nodes 51
theorem unsat41s_c4_1_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c4_1_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c4_1_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c4_1_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 76,615, nodes 15
theorem unsat41s_c4_1_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c4_1_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 79,188, nodes 15
theorem unsat41s_c4_1_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 78,840, nodes 15
theorem unsat41s_c4_1_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c4_1_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 76,815, nodes 15
theorem unsat41s_c4_1_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c4_1_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 79,514, nodes 15
theorem unsat41s_c4_1_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 78,710, nodes 15
theorem unsat41s_c4_1_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 1, 6)` — cap-work 707,936 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_1_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_1_6_s0
  · exact unsat41s_c4_1_6_s1
  · exact unsat41s_c4_1_6_s2
  · exact unsat41s_c4_1_6_s3
  · exact unsat41s_c4_1_6_s4
  · exact unsat41s_c4_1_6_s5
  · exact unsat41s_c4_1_6_s6
  · exact unsat41s_c4_1_6_s7
  · exact unsat41s_c4_1_6_s8
  · exact unsat41s_c4_1_6_s9
  · exact unsat41s_c4_1_6_s10
  · exact unsat41s_c4_1_6_s11
  · exact unsat41s_c4_1_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 78,529, nodes 15
theorem unsat41s_c0_2_0_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_0_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_0_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 157,480, nodes 39
theorem unsat41s_c0_2_0_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 123,214, nodes 27
theorem unsat41s_c0_2_0_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 77,519, nodes 15
theorem unsat41s_c0_2_0_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c0_2_0_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_0_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c0_2_0_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,304, nodes 1
theorem unsat41s_c0_2_0_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 76,969, nodes 15
theorem unsat41s_c0_2_0_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c0_2_0_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 138,920, nodes 37
theorem unsat41s_c0_2_0_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 2, 0)` — cap-work 698,729 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_2_0 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_2_0_s0
  · exact unsat41s_c0_2_0_s1
  · exact unsat41s_c0_2_0_s2
  · exact unsat41s_c0_2_0_s3
  · exact unsat41s_c0_2_0_s4
  · exact unsat41s_c0_2_0_s5
  · exact unsat41s_c0_2_0_s6
  · exact unsat41s_c0_2_0_s7
  · exact unsat41s_c0_2_0_s8
  · exact unsat41s_c0_2_0_s9
  · exact unsat41s_c0_2_0_s10
  · exact unsat41s_c0_2_0_s11
  · exact unsat41s_c0_2_0_s12

end Sharp41
end EuclidsPath
