import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 24/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 54 cells ((4,4,9), (3,3,9), (3,6,2), (0,5,9), (4,4,8), (1,4,2), (2,5,3), (0,1,2), (4,0,1), (1,0,3), (2,1,4), (0,5,3), (1,6,4), (2,0,5), (4,4,2), (1,0,10), (2,1,0), (1,1,9), (2,2,10), (1,4,8), (2,5,9), (0,3,7), (4,2,6), (0,2,8), (4,1,7), (0,2,1), (4,1,0), (3,3,4), (3,0,10), (3,4,4), (0,5,7), (1,4,4), (2,5,5), (3,3,5), (3,3,7), (3,6,4), (3,6,6), (4,4,6), (0,0,2), (0,1,8), (0,5,2), (0,6,2), (0,6,9), (1,1,3), (1,2,9), (1,3,2), (1,3,9), (1,4,9), (2,2,4), (2,3,10), (2,4,3), (2,4,10), (2,5,10), (3,1,5)), 54 kernel gates,
cap-work 7,422,472 (4.3% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 4, 9)` — cap-work 205,331, nodes 39 (measured, re-verified). -/
theorem unsat41s_c4_4_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 3, 9)` — cap-work 181,506, nodes 27 (measured, re-verified). -/
theorem unsat41s_c3_3_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 6, 2)` — cap-work 180,788, nodes 27 (measured, re-verified). -/
theorem unsat41s_c3_6_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 5, 9)` — cap-work 175,327, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_5_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 4, 8)` — cap-work 175,327, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_4_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 4, 2)` — cap-work 174,063, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_4_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 5, 3)` — cap-work 174,063, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_5_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 1, 2)` — cap-work 168,633, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_1_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 0, 1)` — cap-work 168,633, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_0_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 0, 3)` — cap-work 168,525, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_0_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 1, 4)` — cap-work 168,525, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_1_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 5, 3)` — cap-work 168,219, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_5_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 6, 4)` — cap-work 168,219, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_6_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 0, 5)` — cap-work 168,219, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_0_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 4, 2)` — cap-work 168,219, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_4_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 0, 10)` — cap-work 168,047, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_0_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 1, 0)` — cap-work 168,047, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_1_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 1, 9)` — cap-work 167,883, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_1_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 2, 10)` — cap-work 167,883, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_2_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 4, 8)` — cap-work 167,843, nodes 27 (measured, re-verified). -/
theorem unsat41s_c1_4_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 5, 9)` — cap-work 167,843, nodes 27 (measured, re-verified). -/
theorem unsat41s_c2_5_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 3, 7)` — cap-work 167,743, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_3_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 2, 6)` — cap-work 167,743, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_2_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 2, 8)` — cap-work 167,489, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_2_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 1, 7)` — cap-work 167,489, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_1_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 2, 1)` — cap-work 167,335, nodes 27 (measured, re-verified). -/
theorem unsat41s_c0_2_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 1, 0)` — cap-work 167,335, nodes 27 (measured, re-verified). -/
theorem unsat41s_c4_1_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 3, 4)` — cap-work 163,834, nodes 27 (measured, re-verified). -/
theorem unsat41s_c3_3_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 0, 10)` — cap-work 163,490, nodes 27 (measured, re-verified). -/
theorem unsat41s_c3_0_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 0 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 4, 4)` — cap-work 163,183, nodes 27 (measured, re-verified). -/
theorem unsat41s_c3_4_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 5, 7)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_5_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 4, 4)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_4_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 5, 5)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_5_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 3, 5)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c3_3_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 3, 7)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c3_3_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 3 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 6, 4)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c3_6_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 6 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 6, 6)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c3_6_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 4, 6)` — cap-work 97,515, nodes 13 (measured, re-verified). -/
theorem unsat41s_c4_4_6 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 0, 2)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_0_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 1, 8)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_1_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 5, 2)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_5_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 6, 2)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_6_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 6, 9)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c0_6_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 6 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 1, 3)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_1_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 2, 9)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_2_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 3, 2)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_3_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 3, 9)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_3_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 4, 9)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c1_4_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 2, 4)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_2_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 2 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 3, 10)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_3_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 4, 3)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_4_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 4, 10)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_4_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 5, 10)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c2_5_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 1, 5)` — cap-work 95,348, nodes 13 (measured, re-verified). -/
theorem unsat41s_c3_1_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

end Sharp41
end EuclidsPath
