import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 08/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 9 cells ((3,5,3), (1,4,3), (2,5,4), (1,0,4), (2,1,5), (1,6,2), (2,0,3), (3,5,8), (0,0,3)), 126 kernel gates,
cap-work 7,135,191 (4.1% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_3_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c3_5_3_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_3_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 77,065, nodes 15
theorem unsat41s_c3_5_3_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_3_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_3_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 158,023, nodes 39
theorem unsat41s_c3_5_3_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 166,969, nodes 39
theorem unsat41s_c3_5_3_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 163,829, nodes 39
theorem unsat41s_c3_5_3_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 79,102, nodes 15
theorem unsat41s_c3_5_3_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 118,752, nodes 27
theorem unsat41s_c3_5_3_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_3_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,304, nodes 1
theorem unsat41s_c3_5_3_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 5, 3)` — cap-work 809,247 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_5_3 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_5_3_s0
  · exact unsat41s_c3_5_3_s1
  · exact unsat41s_c3_5_3_s2
  · exact unsat41s_c3_5_3_s3
  · exact unsat41s_c3_5_3_s4
  · exact unsat41s_c3_5_3_s5
  · exact unsat41s_c3_5_3_s6
  · exact unsat41s_c3_5_3_s7
  · exact unsat41s_c3_5_3_s8
  · exact unsat41s_c3_5_3_s9
  · exact unsat41s_c3_5_3_s10
  · exact unsat41s_c3_5_3_s11
  · exact unsat41s_c3_5_3_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 82,311, nodes 15
theorem unsat41s_c1_4_3_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,289, nodes 1
theorem unsat41s_c1_4_3_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c1_4_3_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 80,088, nodes 15
theorem unsat41s_c1_4_3_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 178,152, nodes 39
theorem unsat41s_c1_4_3_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,486, nodes 1
theorem unsat41s_c1_4_3_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 130,031, nodes 27
theorem unsat41s_c1_4_3_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,698, nodes 1
theorem unsat41s_c1_4_3_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,092, nodes 1
theorem unsat41s_c1_4_3_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,289, nodes 1
theorem unsat41s_c1_4_3_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 82,323, nodes 15
theorem unsat41s_c1_4_3_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 81,965, nodes 15
theorem unsat41s_c1_4_3_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 126,329, nodes 27
theorem unsat41s_c1_4_3_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 4, 3)` — cap-work 804,145 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_4_3 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 4 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_4_3_s0
  · exact unsat41s_c1_4_3_s1
  · exact unsat41s_c1_4_3_s2
  · exact unsat41s_c1_4_3_s3
  · exact unsat41s_c1_4_3_s4
  · exact unsat41s_c1_4_3_s5
  · exact unsat41s_c1_4_3_s6
  · exact unsat41s_c1_4_3_s7
  · exact unsat41s_c1_4_3_s8
  · exact unsat41s_c1_4_3_s9
  · exact unsat41s_c1_4_3_s10
  · exact unsat41s_c1_4_3_s11
  · exact unsat41s_c1_4_3_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 126,329, nodes 27
theorem unsat41s_c2_5_4_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 82,311, nodes 15
theorem unsat41s_c2_5_4_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,289, nodes 1
theorem unsat41s_c2_5_4_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c2_5_4_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 80,088, nodes 15
theorem unsat41s_c2_5_4_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 178,152, nodes 39
theorem unsat41s_c2_5_4_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,486, nodes 1
theorem unsat41s_c2_5_4_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 130,031, nodes 27
theorem unsat41s_c2_5_4_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c2_5_4_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,092, nodes 1
theorem unsat41s_c2_5_4_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,289, nodes 1
theorem unsat41s_c2_5_4_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 82,323, nodes 15
theorem unsat41s_c2_5_4_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 81,965, nodes 15
theorem unsat41s_c2_5_4_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 5, 4)` — cap-work 804,145 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_5_4 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 5 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_5_4_s0
  · exact unsat41s_c2_5_4_s1
  · exact unsat41s_c2_5_4_s2
  · exact unsat41s_c2_5_4_s3
  · exact unsat41s_c2_5_4_s4
  · exact unsat41s_c2_5_4_s5
  · exact unsat41s_c2_5_4_s6
  · exact unsat41s_c2_5_4_s7
  · exact unsat41s_c2_5_4_s8
  · exact unsat41s_c2_5_4_s9
  · exact unsat41s_c2_5_4_s10
  · exact unsat41s_c2_5_4_s11
  · exact unsat41s_c2_5_4_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_4_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_4_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c1_0_4_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 201,728, nodes 51
theorem unsat41s_c1_0_4_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 79,552, nodes 15
theorem unsat41s_c1_0_4_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 78,194, nodes 15
theorem unsat41s_c1_0_4_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_4_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 119,995, nodes 27
theorem unsat41s_c1_0_4_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_4_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 121,685, nodes 27
theorem unsat41s_c1_0_4_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 79,208, nodes 15
theorem unsat41s_c1_0_4_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_4_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 77,347, nodes 15
theorem unsat41s_c1_0_4_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 0, 4)` — cap-work 798,291 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_0_4 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_0_4_s0
  · exact unsat41s_c1_0_4_s1
  · exact unsat41s_c1_0_4_s2
  · exact unsat41s_c1_0_4_s3
  · exact unsat41s_c1_0_4_s4
  · exact unsat41s_c1_0_4_s5
  · exact unsat41s_c1_0_4_s6
  · exact unsat41s_c1_0_4_s7
  · exact unsat41s_c1_0_4_s8
  · exact unsat41s_c1_0_4_s9
  · exact unsat41s_c1_0_4_s10
  · exact unsat41s_c1_0_4_s11
  · exact unsat41s_c1_0_4_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 77,347, nodes 15
theorem unsat41s_c2_1_5_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_5_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_5_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c2_1_5_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 201,728, nodes 51
theorem unsat41s_c2_1_5_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 79,552, nodes 15
theorem unsat41s_c2_1_5_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 78,194, nodes 15
theorem unsat41s_c2_1_5_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_5_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 119,995, nodes 27
theorem unsat41s_c2_1_5_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_5_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 121,685, nodes 27
theorem unsat41s_c2_1_5_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 79,208, nodes 15
theorem unsat41s_c2_1_5_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_5_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 1, 5)` — cap-work 798,291 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_1_5 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_1_5_s0
  · exact unsat41s_c2_1_5_s1
  · exact unsat41s_c2_1_5_s2
  · exact unsat41s_c2_1_5_s3
  · exact unsat41s_c2_1_5_s4
  · exact unsat41s_c2_1_5_s5
  · exact unsat41s_c2_1_5_s6
  · exact unsat41s_c2_1_5_s7
  · exact unsat41s_c2_1_5_s8
  · exact unsat41s_c2_1_5_s9
  · exact unsat41s_c2_1_5_s10
  · exact unsat41s_c2_1_5_s11
  · exact unsat41s_c2_1_5_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,486, nodes 1
theorem unsat41s_c1_6_2_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 81,017, nodes 15
theorem unsat41s_c1_6_2_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 84,102, nodes 15
theorem unsat41s_c1_6_2_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c1_6_2_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,289, nodes 1
theorem unsat41s_c1_6_2_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 85,473, nodes 15
theorem unsat41s_c1_6_2_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 83,430, nodes 15
theorem unsat41s_c1_6_2_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,428, nodes 15
theorem unsat41s_c1_6_2_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 85,495, nodes 15
theorem unsat41s_c1_6_2_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,683, nodes 1
theorem unsat41s_c1_6_2_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 80,857, nodes 15
theorem unsat41s_c1_6_2_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 83,418, nodes 15
theorem unsat41s_c1_6_2_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 84,470, nodes 15
theorem unsat41s_c1_6_2_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 6, 2)` — cap-work 781,043 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_6_2 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_6_2_s0
  · exact unsat41s_c1_6_2_s1
  · exact unsat41s_c1_6_2_s2
  · exact unsat41s_c1_6_2_s3
  · exact unsat41s_c1_6_2_s4
  · exact unsat41s_c1_6_2_s5
  · exact unsat41s_c1_6_2_s6
  · exact unsat41s_c1_6_2_s7
  · exact unsat41s_c1_6_2_s8
  · exact unsat41s_c1_6_2_s9
  · exact unsat41s_c1_6_2_s10
  · exact unsat41s_c1_6_2_s11
  · exact unsat41s_c1_6_2_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 84,470, nodes 15
theorem unsat41s_c2_0_3_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,486, nodes 1
theorem unsat41s_c2_0_3_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 81,017, nodes 15
theorem unsat41s_c2_0_3_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 84,102, nodes 15
theorem unsat41s_c2_0_3_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,895, nodes 1
theorem unsat41s_c2_0_3_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,289, nodes 1
theorem unsat41s_c2_0_3_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 85,473, nodes 15
theorem unsat41s_c2_0_3_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 83,430, nodes 15
theorem unsat41s_c2_0_3_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 83,428, nodes 15
theorem unsat41s_c2_0_3_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 85,495, nodes 15
theorem unsat41s_c2_0_3_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,683, nodes 1
theorem unsat41s_c2_0_3_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 80,857, nodes 15
theorem unsat41s_c2_0_3_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 83,418, nodes 15
theorem unsat41s_c2_0_3_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 0, 3)` — cap-work 781,043 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_0_3 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_0_3_s0
  · exact unsat41s_c2_0_3_s1
  · exact unsat41s_c2_0_3_s2
  · exact unsat41s_c2_0_3_s3
  · exact unsat41s_c2_0_3_s4
  · exact unsat41s_c2_0_3_s5
  · exact unsat41s_c2_0_3_s6
  · exact unsat41s_c2_0_3_s7
  · exact unsat41s_c2_0_3_s8
  · exact unsat41s_c2_0_3_s9
  · exact unsat41s_c2_0_3_s10
  · exact unsat41s_c2_0_3_s11
  · exact unsat41s_c2_0_3_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 130,472, nodes 27
theorem unsat41s_c3_5_8_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c3_5_8_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 80,547, nodes 15
theorem unsat41s_c3_5_8_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 80,478, nodes 15
theorem unsat41s_c3_5_8_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 209,493, nodes 51
theorem unsat41s_c3_5_8_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c3_5_8_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 80,393, nodes 15
theorem unsat41s_c3_5_8_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 77,864, nodes 15
theorem unsat41s_c3_5_8_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c3_5_8_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,289, nodes 1
theorem unsat41s_c3_5_8_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 80,407, nodes 15
theorem unsat41s_c3_5_8_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c3_5_8_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,698, nodes 1
theorem unsat41s_c3_5_8_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 5, 8)` — cap-work 781,024 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_5_8 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 5 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_5_8_s0
  · exact unsat41s_c3_5_8_s1
  · exact unsat41s_c3_5_8_s2
  · exact unsat41s_c3_5_8_s3
  · exact unsat41s_c3_5_8_s4
  · exact unsat41s_c3_5_8_s5
  · exact unsat41s_c3_5_8_s6
  · exact unsat41s_c3_5_8_s7
  · exact unsat41s_c3_5_8_s8
  · exact unsat41s_c3_5_8_s9
  · exact unsat41s_c3_5_8_s10
  · exact unsat41s_c3_5_8_s11
  · exact unsat41s_c3_5_8_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 78,240, nodes 15
theorem unsat41s_c0_0_3_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 76,251, nodes 15
theorem unsat41s_c0_0_3_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 76,745, nodes 15
theorem unsat41s_c0_0_3_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c0_0_3_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c0_0_3_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 74,004, nodes 15
theorem unsat41s_c0_0_3_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 204,281, nodes 51
theorem unsat41s_c0_0_3_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,092, nodes 1
theorem unsat41s_c0_0_3_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 78,618, nodes 15
theorem unsat41s_c0_0_3_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 76,733, nodes 15
theorem unsat41s_c0_0_3_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 78,812, nodes 15
theorem unsat41s_c0_0_3_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c0_0_3_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,698, nodes 1
theorem unsat41s_c0_0_3_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 0, 3)` — cap-work 777,962 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_0_3 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_0_3_s0
  · exact unsat41s_c0_0_3_s1
  · exact unsat41s_c0_0_3_s2
  · exact unsat41s_c0_0_3_s3
  · exact unsat41s_c0_0_3_s4
  · exact unsat41s_c0_0_3_s5
  · exact unsat41s_c0_0_3_s6
  · exact unsat41s_c0_0_3_s7
  · exact unsat41s_c0_0_3_s8
  · exact unsat41s_c0_0_3_s9
  · exact unsat41s_c0_0_3_s10
  · exact unsat41s_c0_0_3_s11
  · exact unsat41s_c0_0_3_s12

end Sharp41
end EuclidsPath
