import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 12/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 11 cells ((4,5,6), (3,4,8), (3,2,6), (1,0,6), (2,1,7), (0,2,10), (4,1,9), (0,0,7), (4,6,6), (3,4,1), (1,1,0)), 154 kernel gates,
cap-work 7,235,097 (4.2% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,092, nodes 1
theorem unsat41s_c4_5_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 243,917, nodes 61
theorem unsat41s_c4_5_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,289, nodes 1
theorem unsat41s_c4_5_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c4_5_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 7,092, nodes 1
theorem unsat41s_c4_5_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c4_5_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,698, nodes 1
theorem unsat41s_c4_5_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 126,307, nodes 27
theorem unsat41s_c4_5_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,289, nodes 1
theorem unsat41s_c4_5_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,486, nodes 1
theorem unsat41s_c4_5_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 165,899, nodes 39
theorem unsat41s_c4_5_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c4_5_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 80,975, nodes 15
theorem unsat41s_c4_5_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 5, 6)` — cap-work 681,123 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_5_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_5_6_s0
  · exact unsat41s_c4_5_6_s1
  · exact unsat41s_c4_5_6_s2
  · exact unsat41s_c4_5_6_s3
  · exact unsat41s_c4_5_6_s4
  · exact unsat41s_c4_5_6_s5
  · exact unsat41s_c4_5_6_s6
  · exact unsat41s_c4_5_6_s7
  · exact unsat41s_c4_5_6_s8
  · exact unsat41s_c4_5_6_s9
  · exact unsat41s_c4_5_6_s10
  · exact unsat41s_c4_5_6_s11
  · exact unsat41s_c4_5_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_8_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 75,783, nodes 15
theorem unsat41s_c3_4_8_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_8_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_8_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_8_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,304, nodes 1
theorem unsat41s_c3_4_8_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_8_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 76,485, nodes 15
theorem unsat41s_c3_4_8_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 78,868, nodes 15
theorem unsat41s_c3_4_8_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 77,141, nodes 15
theorem unsat41s_c3_4_8_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 75,795, nodes 15
theorem unsat41s_c3_4_8_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 243,847, nodes 63
theorem unsat41s_c3_4_8_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_8_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 4, 8)` — cap-work 673,426 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_4_8 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_4_8_s0
  · exact unsat41s_c3_4_8_s1
  · exact unsat41s_c3_4_8_s2
  · exact unsat41s_c3_4_8_s3
  · exact unsat41s_c3_4_8_s4
  · exact unsat41s_c3_4_8_s5
  · exact unsat41s_c3_4_8_s6
  · exact unsat41s_c3_4_8_s7
  · exact unsat41s_c3_4_8_s8
  · exact unsat41s_c3_4_8_s9
  · exact unsat41s_c3_4_8_s10
  · exact unsat41s_c3_4_8_s11
  · exact unsat41s_c3_4_8_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,895, nodes 1
theorem unsat41s_c3_2_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 75,122, nodes 15
theorem unsat41s_c3_2_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,698, nodes 1
theorem unsat41s_c3_2_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c3_2_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 260,704, nodes 73
theorem unsat41s_c3_2_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 79,552, nodes 15
theorem unsat41s_c3_2_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 75,981, nodes 15
theorem unsat41s_c3_2_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 116,476, nodes 27
theorem unsat41s_c3_2_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,304, nodes 1
theorem unsat41s_c3_2_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,501, nodes 1
theorem unsat41s_c3_2_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 2, 6)` — cap-work 660,434 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_2_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_2_6_s0
  · exact unsat41s_c3_2_6_s1
  · exact unsat41s_c3_2_6_s2
  · exact unsat41s_c3_2_6_s3
  · exact unsat41s_c3_2_6_s4
  · exact unsat41s_c3_2_6_s5
  · exact unsat41s_c3_2_6_s6
  · exact unsat41s_c3_2_6_s7
  · exact unsat41s_c3_2_6_s8
  · exact unsat41s_c3_2_6_s9
  · exact unsat41s_c3_2_6_s10
  · exact unsat41s_c3_2_6_s11
  · exact unsat41s_c3_2_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,501, nodes 1
theorem unsat41s_c1_0_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 292,866, nodes 83
theorem unsat41s_c1_0_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 77,179, nodes 15
theorem unsat41s_c1_0_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 6,895, nodes 1
theorem unsat41s_c1_0_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 80,014, nodes 15
theorem unsat41s_c1_0_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 79,184, nodes 15
theorem unsat41s_c1_0_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c1_0_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c1_0_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 74,620, nodes 15
theorem unsat41s_c1_0_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 0, 6)` — cap-work 658,038 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_0_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_0_6_s0
  · exact unsat41s_c1_0_6_s1
  · exact unsat41s_c1_0_6_s2
  · exact unsat41s_c1_0_6_s3
  · exact unsat41s_c1_0_6_s4
  · exact unsat41s_c1_0_6_s5
  · exact unsat41s_c1_0_6_s6
  · exact unsat41s_c1_0_6_s7
  · exact unsat41s_c1_0_6_s8
  · exact unsat41s_c1_0_6_s9
  · exact unsat41s_c1_0_6_s10
  · exact unsat41s_c1_0_6_s11
  · exact unsat41s_c1_0_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 74,620, nodes 15
theorem unsat41s_c2_1_7_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_7_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,501, nodes 1
theorem unsat41s_c2_1_7_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_7_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 292,866, nodes 83
theorem unsat41s_c2_1_7_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_7_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 77,179, nodes 15
theorem unsat41s_c2_1_7_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 6,895, nodes 1
theorem unsat41s_c2_1_7_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 80,014, nodes 15
theorem unsat41s_c2_1_7_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 79,184, nodes 15
theorem unsat41s_c2_1_7_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_7_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,698, nodes 1
theorem unsat41s_c2_1_7_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,092, nodes 1
theorem unsat41s_c2_1_7_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (2, 1, 7)` — cap-work 658,038 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c2_1_7 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c2_1_7_s0
  · exact unsat41s_c2_1_7_s1
  · exact unsat41s_c2_1_7_s2
  · exact unsat41s_c2_1_7_s3
  · exact unsat41s_c2_1_7_s4
  · exact unsat41s_c2_1_7_s5
  · exact unsat41s_c2_1_7_s6
  · exact unsat41s_c2_1_7_s7
  · exact unsat41s_c2_1_7_s8
  · exact unsat41s_c2_1_7_s9
  · exact unsat41s_c2_1_7_s10
  · exact unsat41s_c2_1_7_s11
  · exact unsat41s_c2_1_7_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,289, nodes 1
theorem unsat41s_c0_2_10_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 80,865, nodes 15
theorem unsat41s_c0_2_10_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,289, nodes 1
theorem unsat41s_c0_2_10_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 79,674, nodes 15
theorem unsat41s_c0_2_10_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 6,895, nodes 1
theorem unsat41s_c0_2_10_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 124,279, nodes 27
theorem unsat41s_c0_2_10_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,289, nodes 1
theorem unsat41s_c0_2_10_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,092, nodes 1
theorem unsat41s_c0_2_10_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 80,853, nodes 15
theorem unsat41s_c0_2_10_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 81,173, nodes 15
theorem unsat41s_c0_2_10_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 81,201, nodes 15
theorem unsat41s_c0_2_10_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,289, nodes 1
theorem unsat41s_c0_2_10_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 81,711, nodes 15
theorem unsat41s_c0_2_10_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 2, 10)` — cap-work 652,899 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_2_10 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 2 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_2_10_s0
  · exact unsat41s_c0_2_10_s1
  · exact unsat41s_c0_2_10_s2
  · exact unsat41s_c0_2_10_s3
  · exact unsat41s_c0_2_10_s4
  · exact unsat41s_c0_2_10_s5
  · exact unsat41s_c0_2_10_s6
  · exact unsat41s_c0_2_10_s7
  · exact unsat41s_c0_2_10_s8
  · exact unsat41s_c0_2_10_s9
  · exact unsat41s_c0_2_10_s10
  · exact unsat41s_c0_2_10_s11
  · exact unsat41s_c0_2_10_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 80,865, nodes 15
theorem unsat41s_c4_1_9_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,289, nodes 1
theorem unsat41s_c4_1_9_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 79,674, nodes 15
theorem unsat41s_c4_1_9_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,895, nodes 1
theorem unsat41s_c4_1_9_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 124,279, nodes 27
theorem unsat41s_c4_1_9_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,289, nodes 1
theorem unsat41s_c4_1_9_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c4_1_9_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 80,853, nodes 15
theorem unsat41s_c4_1_9_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 81,173, nodes 15
theorem unsat41s_c4_1_9_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 81,201, nodes 15
theorem unsat41s_c4_1_9_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 7,289, nodes 1
theorem unsat41s_c4_1_9_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 81,711, nodes 15
theorem unsat41s_c4_1_9_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,289, nodes 1
theorem unsat41s_c4_1_9_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 1, 9)` — cap-work 652,899 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_1_9 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 1 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_1_9_s0
  · exact unsat41s_c4_1_9_s1
  · exact unsat41s_c4_1_9_s2
  · exact unsat41s_c4_1_9_s3
  · exact unsat41s_c4_1_9_s4
  · exact unsat41s_c4_1_9_s5
  · exact unsat41s_c4_1_9_s6
  · exact unsat41s_c4_1_9_s7
  · exact unsat41s_c4_1_9_s8
  · exact unsat41s_c4_1_9_s9
  · exact unsat41s_c4_1_9_s10
  · exact unsat41s_c4_1_9_s11
  · exact unsat41s_c4_1_9_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 78,406, nodes 15
theorem unsat41s_c0_0_7_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 79,352, nodes 15
theorem unsat41s_c0_0_7_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c0_0_7_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 7,289, nodes 1
theorem unsat41s_c0_0_7_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 75,991, nodes 15
theorem unsat41s_c0_0_7_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 79,332, nodes 15
theorem unsat41s_c0_0_7_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 81,739, nodes 15
theorem unsat41s_c0_0_7_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 7,092, nodes 1
theorem unsat41s_c0_0_7_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 209,183, nodes 51
theorem unsat41s_c0_0_7_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c0_0_7_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c0_0_7_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c0_0_7_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,092, nodes 1
theorem unsat41s_c0_0_7_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (0, 0, 7)` — cap-work 652,662 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c0_0_7 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c0_0_7_s0
  · exact unsat41s_c0_0_7_s1
  · exact unsat41s_c0_0_7_s2
  · exact unsat41s_c0_0_7_s3
  · exact unsat41s_c0_0_7_s4
  · exact unsat41s_c0_0_7_s5
  · exact unsat41s_c0_0_7_s6
  · exact unsat41s_c0_0_7_s7
  · exact unsat41s_c0_0_7_s8
  · exact unsat41s_c0_0_7_s9
  · exact unsat41s_c0_0_7_s10
  · exact unsat41s_c0_0_7_s11
  · exact unsat41s_c0_0_7_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 79,352, nodes 15
theorem unsat41s_c4_6_6_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,895, nodes 1
theorem unsat41s_c4_6_6_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,289, nodes 1
theorem unsat41s_c4_6_6_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 75,991, nodes 15
theorem unsat41s_c4_6_6_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 79,332, nodes 15
theorem unsat41s_c4_6_6_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 81,739, nodes 15
theorem unsat41s_c4_6_6_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 7,092, nodes 1
theorem unsat41s_c4_6_6_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 209,183, nodes 51
theorem unsat41s_c4_6_6_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 6,698, nodes 1
theorem unsat41s_c4_6_6_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 6,698, nodes 1
theorem unsat41s_c4_6_6_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,895, nodes 1
theorem unsat41s_c4_6_6_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 7,092, nodes 1
theorem unsat41s_c4_6_6_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 78,406, nodes 15
theorem unsat41s_c4_6_6_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (4, 6, 6)` — cap-work 652,662 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c4_6_6 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 6 (strikeFilter 7 6 6 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c4_6_6_s0
  · exact unsat41s_c4_6_6_s1
  · exact unsat41s_c4_6_6_s2
  · exact unsat41s_c4_6_6_s3
  · exact unsat41s_c4_6_6_s4
  · exact unsat41s_c4_6_6_s5
  · exact unsat41s_c4_6_6_s6
  · exact unsat41s_c4_6_6_s7
  · exact unsat41s_c4_6_6_s8
  · exact unsat41s_c4_6_6_s9
  · exact unsat41s_c4_6_6_s10
  · exact unsat41s_c4_6_6_s11
  · exact unsat41s_c4_6_6_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 158,290, nodes 39
theorem unsat41s_c3_4_1_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_1_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 6,895, nodes 1
theorem unsat41s_c3_4_1_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_1_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 75,657, nodes 15
theorem unsat41s_c3_4_1_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 6,501, nodes 1
theorem unsat41s_c3_4_1_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 165,872, nodes 39
theorem unsat41s_c3_4_1_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 78,918, nodes 15
theorem unsat41s_c3_4_1_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,092, nodes 1
theorem unsat41s_c3_4_1_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 118,031, nodes 27
theorem unsat41s_c3_4_1_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_1_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 6,895, nodes 1
theorem unsat41s_c3_4_1_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 6,698, nodes 1
theorem unsat41s_c3_4_1_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (3, 4, 1)` — cap-work 650,746 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c3_4_1 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 4 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c3_4_1_s0
  · exact unsat41s_c3_4_1_s1
  · exact unsat41s_c3_4_1_s2
  · exact unsat41s_c3_4_1_s3
  · exact unsat41s_c3_4_1_s4
  · exact unsat41s_c3_4_1_s5
  · exact unsat41s_c3_4_1_s6
  · exact unsat41s_c3_4_1_s7
  · exact unsat41s_c3_4_1_s8
  · exact unsat41s_c3_4_1_s9
  · exact unsat41s_c3_4_1_s10
  · exact unsat41s_c3_4_1_s11
  · exact unsat41s_c3_4_1_s12

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 0: cap-work 7,289, nodes 1
theorem unsat41s_c1_1_0_s0 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 0 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 1: cap-work 7,092, nodes 1
theorem unsat41s_c1_1_0_s1 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 1 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 2: cap-work 7,092, nodes 1
theorem unsat41s_c1_1_0_s2 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 2 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 3: cap-work 83,906, nodes 15
theorem unsat41s_c1_1_0_s3 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 3 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 4: cap-work 85,879, nodes 15
theorem unsat41s_c1_1_0_s4 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 4 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 5: cap-work 7,092, nodes 1
theorem unsat41s_c1_1_0_s5 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 5 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 6: cap-work 83,810, nodes 15
theorem unsat41s_c1_1_0_s6 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 6 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 7: cap-work 171,820, nodes 39
theorem unsat41s_c1_1_0_s7 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 7 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 8: cap-work 7,486, nodes 1
theorem unsat41s_c1_1_0_s8 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 8 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 9: cap-work 7,289, nodes 1
theorem unsat41s_c1_1_0_s9 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 9 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 10: cap-work 84,154, nodes 15
theorem unsat41s_c1_1_0_s10 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 10 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 11: cap-work 81,775, nodes 15
theorem unsat41s_c1_1_0_s11 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 11 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- sub-cell t13 = 12: cap-work 7,486, nodes 1
theorem unsat41s_c1_1_0_s12 :
    enumSmallB [] bigs41
      (strikeFilter 13 11 12 (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120))))) = true := by
  decide +kernel

/-- Cell `(t5, t7, t11) = (1, 1, 0)` — cap-work 642,170 > 600,000:
    split by the `t13` phase into 13 kernel sub-cells (sums re-verified exact). -/
theorem unsat41s_c1_1_0 :
    enumSmallB ((13, 11) :: []) bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 1 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  refine enumSmall_cons_of_parts ?_
  intro t ht
  interval_cases t
  · exact unsat41s_c1_1_0_s0
  · exact unsat41s_c1_1_0_s1
  · exact unsat41s_c1_1_0_s2
  · exact unsat41s_c1_1_0_s3
  · exact unsat41s_c1_1_0_s4
  · exact unsat41s_c1_1_0_s5
  · exact unsat41s_c1_1_0_s6
  · exact unsat41s_c1_1_0_s7
  · exact unsat41s_c1_1_0_s8
  · exact unsat41s_c1_1_0_s9
  · exact unsat41s_c1_1_0_s10
  · exact unsat41s_c1_1_0_s11
  · exact unsat41s_c1_1_0_s12

end Sharp41
end EuclidsPath
