import EuclidsPath.Engine.Step00GapBracket4143

-- GENERATED by tools/gen_sharp41_lean.py -- do not edit by hand; regenerate instead.

set_option autoImplicit false
set_option linter.unusedVariables false

/-!
# Sharp-41 kernel ladder — Part 20/25 (generated)

Per-cell UNSAT kernel certificates for the phase-cover problem at `A = 41`,
`g = 120 = ⌊41²/14⌋` (the Sharp window).  Each theorem replays the measured cell
`(t5, t7, t11)` of `tools/sharp41_cells.json` through the verified checker of
`Step00PhaseCoverKernel` (`enumSmallB`/`dfsB`, phases pinned by order-preserving
`strikeFilter` prefixes — the decomposition is exact by construction and every cell
was re-solved by `tools/gen_sharp41_lean.py` before emission).  Cells above
600,000 cap-work are split by the `t13` phase and glued back by
`enumSmall_cons_of_parts` in this same part.

This part: 20 cells ((2,4,2), (0,6,3), (4,5,2), (1,3,8), (2,4,9), (0,4,0), (1,0,7), (2,1,8), (3,2,9), (4,3,10), (1,6,1), (2,0,2), (3,1,3), (0,3,10), (3,1,8), (4,2,9), (0,5,0), (4,4,10), (0,1,5), (4,0,4)), 20 kernel gates,
cap-work 7,469,945 (4.3% of the ladder's 174,254,797).
-/

namespace EuclidsPath
namespace Sharp41

open EuclidsPath.PhaseCoverKernel
open EuclidsPath.GapBracket4143

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 4, 2)` — cap-work 383,911, nodes 79 (measured, re-verified). -/
theorem unsat41s_c2_4_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 6, 3)` — cap-work 381,599, nodes 69 (measured, re-verified). -/
theorem unsat41s_c0_6_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 6 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 5, 2)` — cap-work 381,599, nodes 69 (measured, re-verified). -/
theorem unsat41s_c4_5_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 5 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 3, 8)` — cap-work 381,463, nodes 69 (measured, re-verified). -/
theorem unsat41s_c1_3_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 3 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 4, 9)` — cap-work 381,463, nodes 69 (measured, re-verified). -/
theorem unsat41s_c2_4_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 4 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 4, 0)` — cap-work 381,024, nodes 79 (measured, re-verified). -/
theorem unsat41s_c0_4_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 4 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 0, 7)` — cap-work 381,024, nodes 79 (measured, re-verified). -/
theorem unsat41s_c1_0_7 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 7 (strikeFilter 7 6 0 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 1, 8)` — cap-work 381,024, nodes 79 (measured, re-verified). -/
theorem unsat41s_c2_1_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 1 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 2, 9)` — cap-work 381,024, nodes 79 (measured, re-verified). -/
theorem unsat41s_c3_2_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 3, 10)` — cap-work 381,024, nodes 79 (measured, re-verified). -/
theorem unsat41s_c4_3_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (1, 6, 1)` — cap-work 376,002, nodes 67 (measured, re-verified). -/
theorem unsat41s_c1_6_1 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 1 (strikeFilter 7 6 6 (strikeFilter 5 1 1 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (2, 0, 2)` — cap-work 376,002, nodes 67 (measured, re-verified). -/
theorem unsat41s_c2_0_2 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 2 (strikeFilter 7 6 0 (strikeFilter 5 1 2 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 1, 3)` — cap-work 376,002, nodes 67 (measured, re-verified). -/
theorem unsat41s_c3_1_3 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 3 (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 3, 10)` — cap-work 375,912, nodes 67 (measured, re-verified). -/
theorem unsat41s_c0_3_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 3 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (3, 1, 8)` — cap-work 375,912, nodes 67 (measured, re-verified). -/
theorem unsat41s_c3_1_8 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 8 (strikeFilter 7 6 1 (strikeFilter 5 1 3 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 2, 9)` — cap-work 375,912, nodes 67 (measured, re-verified). -/
theorem unsat41s_c4_2_9 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 9 (strikeFilter 7 6 2 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 5, 0)` — cap-work 352,018, nodes 65 (measured, re-verified). -/
theorem unsat41s_c0_5_0 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 0 (strikeFilter 7 6 5 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 4, 10)` — cap-work 352,018, nodes 65 (measured, re-verified). -/
theorem unsat41s_c4_4_10 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 10 (strikeFilter 7 6 4 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (0, 1, 5)` — cap-work 347,506, nodes 67 (measured, re-verified). -/
theorem unsat41s_c0_1_5 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 5 (strikeFilter 7 6 1 (strikeFilter 5 1 0 (List.range' 1 120)))) = true := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell `(t5, t7, t11) = (4, 0, 4)` — cap-work 347,506, nodes 67 (measured, re-verified). -/
theorem unsat41s_c4_0_4 :
    enumSmallB [(13, 11)] bigs41
      (strikeFilter 11 2 4 (strikeFilter 7 6 0 (strikeFilter 5 1 4 (List.range' 1 120)))) = true := by
  decide +kernel

end Sharp41
end EuclidsPath
